---@meta
Enum = {
	---@enum AddSoulbindConduitReason
	AddSoulbindConduitReason = {
		None = 0,
		Cheat = 1,
		SpellEffect = 2,
		Upgrade = 3,
	},
	---@enum AnimaDiversionNodeState
	AnimaDiversionNodeState = {
		Unavailable = 0,
		Available = 1,
		SelectedTemporary = 2,
		SelectedPermanent = 3,
		Cooldown = 4,
	},
	---@enum AuctionHouseCommoditySortOrder
	AuctionHouseCommoditySortOrder = {
		UnitPrice = 0,
		Quantity = 1,
	},
	---@enum AuctionHouseError
	AuctionHouseError = {
		NotEnoughMoney = 0,
		HigherBid = 1,
		BidIncrement = 2,
		BidOwn = 3,
		ItemNotFound = 4,
		RestrictedAccountTrial = 5,
		HasRestriction = 6,
		IsBusy = 7,
		Unavailable = 8,
		ItemHasQuote = 9,
		DatabaseError = 10,
		MinBid = 11,
		NotEnoughItems = 12,
		RepairItem = 13,
		UsedCharges = 14,
		QuestItem = 15,
		BoundItem = 16,
		ConjuredItem = 17,
		LimitedDurationItem = 18,
		IsBag = 19,
		EquippedBag = 20,
		WrappedItem = 21,
		LootItem = 22,
	},
	---@enum AuctionHouseFilter
	AuctionHouseFilter = {
		None = 0,
		UncollectedOnly = 1,
		UsableOnly = 2,
		UpgradesOnly = 3,
		ExactMatch = 4,
		PoorQuality = 5,
		CommonQuality = 6,
		UncommonQuality = 7,
		RareQuality = 8,
		EpicQuality = 9,
		LegendaryQuality = 10,
		ArtifactQuality = 11,
		LegendaryCraftedItemOnly = 12,
	},
	---@enum AuctionHouseFilterCategory
	AuctionHouseFilterCategory = {
		Uncategorized = 0,
		Equipment = 1,
		Rarity = 2,
	},
	---@enum AuctionHouseItemSortOrder
	AuctionHouseItemSortOrder = {
		Bid = 0,
		Buyout = 1,
	},
	---@enum AuctionHouseNotification
	AuctionHouseNotification = {
		BidPlaced = 0,
		AuctionRemoved = 1,
		AuctionWon = 2,
		AuctionOutbid = 3,
		AuctionSold = 4,
		AuctionExpired = 5,
	},
	---@enum AuctionHouseSortOrder
	AuctionHouseSortOrder = {
		Price = 0,
		Name = 1,
		Level = 2,
		Bid = 3,
		Buyout = 4,
		TimeRemaining = 5,
	},
	---@enum AuctionHouseTimeLeftBand
	AuctionHouseTimeLeftBand = {
		Short = 0,
		Medium = 1,
		Long = 2,
		VeryLong = 3,
	},
	---@enum AuctionStatus
	AuctionStatus = {
		Active = 0,
		Sold = 1,
	},
	---@enum AzeriteEssenceSlot
	AzeriteEssenceSlot = {
		MainSlot = 0,
		PassiveOneSlot = 1,
		PassiveTwoSlot = 2,
		PassiveThreeSlot = 3,
	},
	---@enum AzeritePowerLevel
	AzeritePowerLevel = {
		Base = 0,
		Upgraded = 1,
		Downgraded = 2,
	},
	---@enum BattlePetAbilityFlag
	BattlePetAbilityFlag = {
		DisplayAsHostileDebuff = 1,
		HideStrongWeakHints = 2,
		Passive = 4,
		ServerOnlyAura = 8,
		ShowCast = 16,
		StartOnCooldown = 32,
	},
	---@enum BattlePetAbilitySlot
	BattlePetAbilitySlot = {
		A = 0,
		B = 1,
		C = 2,
	},
	---@enum BattlePetAbilityTargets
	BattlePetAbilityTargets = {
		EnemyFrontPet = 0,
		FriendlyFrontPet = 1,
		Weather = 2,
		EnemyPad = 3,
		FriendlyPad = 4,
		EnemyBackPet_1 = 5,
		EnemyBackPet_2 = 6,
		FriendlyBackPet_1 = 7,
		FriendlyBackPet_2 = 8,
		Caster = 9,
		Owner = 10,
		Specific = 11,
		ProcTarget = 12,
	},
	---@enum BattlePetAbilityTurnFlag
	BattlePetAbilityTurnFlag = {
		CanProcFromProc = 1,
		TriggerBySelf = 2,
		TriggerByFriend = 4,
		TriggerByEnemy = 8,
		TriggerByWeather = 16,
		TriggerByAuraCaster = 32,
	},
	---@enum BattlePetAbilityTurnType
	BattlePetAbilityTurnType = {
		Normal = 0,
		TriggeredEffect = 1,
	},
	---@enum BattlePetAbilityType
	BattlePetAbilityType = {
		Ability = 0,
		Aura = 1,
	},
	---@enum BattlePetAction
	BattlePetAction = {
		None = 0,
		Ability = 1,
		SwitchPet = 2,
		Trap = 3,
		Skip = 4,
	},
	---@enum BattlePetBreedQuality
	BattlePetBreedQuality = {
		Poor = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
	},
	---@enum BattlePetEffectFlags
	BattlePetEffectFlags = {
		EnableAbilityPicker = 1,
		LuaNeedsAllPets = 2,
	},
	---@enum BattlePetEffectParamType
	BattlePetEffectParamType = {
		Int = 0,
		Ability = 1,
	},
	---@enum BattlePetEvent
	BattlePetEvent = {
		OnAuraApplied = 0,
		OnDamageTaken = 1,
		OnDamageDealt = 2,
		OnHealTaken = 3,
		OnHealDealt = 4,
		OnAuraRemoved = 5,
		OnRoundStart = 6,
		OnRoundEnd = 7,
		OnTurn = 8,
		OnAbility = 9,
		OnSwapIn = 10,
		OnSwapOut = 11,
		PostAuraTicks = 12,
	},
	---@enum BattlePetNpcEmote
	BattlePetNpcEmote = {
		BattleUnused = 0,
		BattleStart = 1,
		BattleWin = 2,
		BattleLose = 3,
		PetSwap = 4,
		PetKill = 5,
		PetDie = 6,
		PetAbility = 7,
	},
	---@enum BattlePetNpcTeamFlag
	BattlePetNpcTeamFlag = {
		MatchPlayerHighPetLevel = 1,
		NoPlayerXP = 2,
	},
	---@enum BattlePetOwner
	BattlePetOwner = {
		Weather = 0,
		Ally = 1,
		Enemy = 2,
	},
	---@enum BattlePetSources
	BattlePetSources = {
		Drop = 0,
		Quest = 1,
		Vendor = 2,
		Profession = 3,
		WildPet = 4,
		Achievement = 5,
		WorldEvent = 6,
		Promotion = 7,
		Tcg = 8,
		PetStore = 9,
		Discovery = 10,
	},
	---@enum BattlePetSpeciesFlags
	BattlePetSpeciesFlags = {
		NoRename = 1,
		WellKnown = 2,
		NotAcccountwide = 4,
		Capturable = 8,
		NotTradable = 16,
		HideFromJournal = 32,
		LegacyAccountUnique = 64,
		CantBattle = 128,
		HordeOnly = 256,
		AllianceOnly = 512,
		Boss = 1024,
		RandomDisplay = 2048,
		NoLicenseRequired = 4096,
		AddsAllowedWithBoss = 8192,
		HideUntilLearned = 16384,
		MatchPlayerHighPetLevel = 32768,
	},
	---@enum BattlePetStateFlag
	BattlePetStateFlag = {
		None = 0,
		SwapOutLock = 1,
		TurnLock = 2,
		SpeedBonus = 4,
		Client = 8,
		MaxHealthBonus = 16,
		Stamina = 32,
		QualityDoesNotEffect = 64,
		DynamicScaling = 128,
		Power = 256,
		SpeedMult = 512,
		SwapInLock = 1024,
		ServerOnly = 2048,
	},
	---@enum BattlePetTypes
	BattlePetTypes = {
		Humanoid = 0,
		Dragonkin = 1,
		Flying = 2,
		Undead = 3,
		Critter = 4,
		Magic = 5,
		Elemental = 6,
		Beast = 7,
		Aquatic = 8,
		Mechanical = 9,
	},
	---@enum BattlePetVisualFlag
	BattlePetVisualFlag = {
		Test1 = 1,
		Test2 = 2,
		Test3 = 4,
	},
	---@enum BattlePetVisualRange
	BattlePetVisualRange = {
		Melee = 0,
		Ranged = 1,
		InPlace = 2,
		PointBlank = 3,
		BehindMelee = 4,
		BehindRanged = 5,
	},
	---@enum BattlepetDbFlags
	BattlepetDbFlags = {
		None = 0,
		Favorite = 1,
		Converted = 2,
		Revoked = 4,
		LockedForConvert = 8,
		LockMask = 12,
		Ability0Selection = 16,
		Ability1Selection = 32,
		Ability2Selection = 64,
		FanfareNeeded = 128,
		DisplayOverridden = 256,
	},
	---@enum BattlepetDeletedReason
	BattlepetDeletedReason = {
		Unknown = 0,
		PlayerReleased = 1,
		PlayerCaged = 2,
		Gm = 3,
		CageError = 4,
		DelJournal = 5,
	},
	---@enum BattlepetSlotLockCheat
	BattlepetSlotLockCheat = {
		Cheat_2_Locked = -3,
		Cheat_1_Locked = -2,
		Cheat_0_Locked = -1,
		CheatOff = 0,
		UnlockAll = 1,
	},
	---@enum BrawlType
	BrawlType = {
		None = 0,
		Battleground = 1,
		Arena = 2,
		LFG = 3,
		SoloShuffle = 4,
	},
	---@enum CachedRewardType
	CachedRewardType = {
		None = 0,
		Item = 1,
		Currency = 2,
		Quest = 3,
	},
	---@enum CalendarCommandType
	CalendarCommandType = {
		Create = 0,
		Invite = 1,
		Rsvp = 2,
		RemoveInvite = 3,
		RemoveEvent = 4,
		Status = 5,
		ModeratorStatus = 6,
		GetCalendar = 7,
		GetEvent = 8,
		UpdateEvent = 9,
		Complain = 10,
		Notes = 11,
	},
	---@enum CalendarErrorType
	CalendarErrorType = {
		Success = 0,
		CommunityEventsExceeded = 1,
		EventsExceeded = 2,
		SelfInvitesExceeded = 3,
		OtherInvitesExceeded = 4,
		NoPermission = 5,
		EventInvalid = 6,
		NotInvited = 7,
		UnknownError = 8,
		NotInGuild = 9,
		NotInCommunity = 10,
		TargetAlreadyInvited = 11,
		NameNotFound = 12,
		WrongFaction = 13,
		Ignored = 14,
		InvitesExceeded = 15,
		InvalidMaxSize = 16,
		InvalidDate = 17,
		InvalidTime = 18,
		NoInvites = 19,
		NeedsTitle = 20,
		EventPassed = 21,
		EventLocked = 22,
		DeleteCreatorFailed = 23,
		DataAlreadySet = 24,
		CalendarDisabled = 25,
		RestrictedAccount = 26,
		ArenaEventsExceeded = 27,
		RestrictedLevel = 28,
		Squelched = 29,
		NoInvite = 30,
		ComplaintDisabled = 31,
		ComplaintSelf = 32,
		ComplaintSameGuild = 33,
		ComplaintGm = 34,
		ComplaintLimit = 35,
		ComplaintNotFound = 36,
		EventWrongServer = 37,
		NoCommunityInvites = 38,
		InvalidSignup = 39,
		NoModerator = 40,
		ModeratorRestricted = 41,
		InvalidNotes = 42,
		InvalidTitle = 43,
		InvalidDescription = 44,
		InvalidClub = 45,
		CreatorNotFound = 46,
		EventThrottled = 47,
		InviteThrottled = 48,
		Internal = 49,
		ComplaintAdded = 50,
	},
	---@enum CalendarEventBits
	CalendarEventBits = {
		Player = 1,
		GuildDeprecated = 2,
		System = 4,
		Holiday = 8,
		Locked = 16,
		AutoApprove = 32,
		CommunityAnnouncement = 64,
		RaidLockout = 128,
		ArenaDeprecated = 256,
		RaidResetDeprecated = 512,
		CommunitySignup = 1024,
		GuildSignup = 2048,
		CommunityWide = 3136,
		PlayerCreated = 3395,
		CantComplain = 3788,
	},
	---@enum CalendarEventRepeatOptions
	CalendarEventRepeatOptions = {
		Never = 0,
		Weekly = 1,
		Biweekly = 2,
		Monthly = 3,
	},
	---@enum CalendarEventType
	CalendarEventType = {
		Raid = 0,
		Dungeon = 1,
		PvP = 2,
		Meeting = 3,
		Other = 4,
		HeroicDeprecated = 5,
	},
	---@enum CalendarFilterFlags
	CalendarFilterFlags = {
		WeeklyHoliday = 1,
		Darkmoon = 2,
		Battleground = 4,
		RaidLockout = 8,
		RaidReset = 16,
	},
	---@enum CalendarGetEventType
	CalendarGetEventType = {
		Get = 0,
		Add = 1,
		Copy = 2,
	},
	---@enum CalendarHolidayFilterType
	CalendarHolidayFilterType = {
		Weekly = 0,
		Darkmoon = 1,
		Battleground = 2,
	},
	---@enum CalendarInviteBits
	CalendarInviteBits = {
		PendingInvite = 1,
		Moderator = 2,
		Creator = 4,
		Signup = 8,
	},
	---@enum CalendarInviteSortType
	CalendarInviteSortType = {
		Name = 0,
		Level = 1,
		Class = 2,
		Status = 3,
		Party = 4,
		Notes = 5,
	},
	---@enum CalendarInviteType
	CalendarInviteType = {
		Normal = 0,
		Signup = 1,
	},
	---@enum CalendarModeratorStatus
	CalendarModeratorStatus = {
		None = 0,
		Moderator = 1,
		Creator = 2,
	},
	---@enum CalendarStatus
	CalendarStatus = {
		Invited = 0,
		Available = 1,
		Declined = 2,
		Confirmed = 3,
		Out = 4,
		Standby = 5,
		Signedup = 6,
		NotSignedup = 7,
		Tentative = 8,
	},
	---@enum CalendarTexturesType
	CalendarTexturesType = {
		Dungeons = 0,
		Raid = 1,
	},
	---@enum CalendarType
	CalendarType = {
		Player = 0,
		Community = 1,
		RaidLockout = 2,
		RaidResetDeprecated = 3,
		Holiday = 4,
		HolidayWeekly = 5,
		HolidayDarkmoon = 6,
		HolidayBattleground = 7,
	},
	---@enum CalendarWebActionType
	CalendarWebActionType = {
		Accept = 0,
		Decline = 1,
		Remove = 2,
		ReportSpam = 3,
		Signup = 4,
		Tentative = 5,
		TentativeSignup = 6,
	},
	---@enum CallingStates
	CallingStates = {
		QuestOffer = 0,
		QuestActive = 1,
		QuestCompleted = 2,
	},
	---@enum CampaignState
	CampaignState = {
		Invalid = 0,
		Complete = 1,
		InProgress = 2,
		Stalled = 3,
	},
	---@enum CaptureBarWidgetFillDirectionType
	CaptureBarWidgetFillDirectionType = {
		RightToLeft = 0,
		LeftToRight = 1,
	},
	---@enum CaptureBarWidgetGlowAnimType
	CaptureBarWidgetGlowAnimType = {
		None = 0,
		Pulse = 1,
	},
	---@enum CharacterServiceInfoFlag
	CharacterServiceInfoFlag = {
		RestrictToRecommendedSpecs = 1,
	},
	---@enum ChatChannelRuleset
	ChatChannelRuleset = {
		None = 0,
		Mentor = 1,
		Disabled = 2,
		ChromieTimeCataclysm = 3,
		ChromieTimeBuringCrusade = 4,
		ChromieTimeWrath = 5,
		ChromieTimeMists = 6,
		ChromieTimeWoD = 7,
		ChromieTimeLegion = 8,
	},
	---@enum ChatChannelType
	ChatChannelType = {
		None = 0,
		Custom = 1,
		Private_Party = 2,
		Public_Party = 3,
		Communities = 4,
	},
	---@enum ChrCustomizationCategoryFlag
	ChrCustomizationCategoryFlag = {
		UndressModel = 1,
	},
	---@enum ChrCustomizationOptionType
	ChrCustomizationOptionType = {
		SelectionPopout = 0,
		Checkbox = 1,
		Slider = 2,
	},
	---@enum ClickBindingInteraction
	ClickBindingInteraction = {
		Target = 1,
		OpenContextMenu = 2,
	},
	---@enum ClickBindingType
	ClickBindingType = {
		None = 0,
		Spell = 1,
		Macro = 2,
		Interaction = 3,
	},
	---@enum ClientPlatformType
	ClientPlatformType = {
		Windows = 0,
		Macintosh = 1,
	},
	---@enum ClientSceneType
	ClientSceneType = {
		DefaultSceneType = 0,
		MinigameSceneType = 1,
	},
	---@enum ClubActionType
	ClubActionType = {
		ErrorClubActionSubscribe = 0,
		ErrorClubActionCreate = 1,
		ErrorClubActionEdit = 2,
		ErrorClubActionDestroy = 3,
		ErrorClubActionLeave = 4,
		ErrorClubActionCreateTicket = 5,
		ErrorClubActionDestroyTicket = 6,
		ErrorClubActionRedeemTicket = 7,
		ErrorClubActionGetTicket = 8,
		ErrorClubActionGetTickets = 9,
		ErrorClubActionGetBans = 10,
		ErrorClubActionGetInvitations = 11,
		ErrorClubActionRevokeInvitation = 12,
		ErrorClubActionAcceptInvitation = 13,
		ErrorClubActionDeclineInvitation = 14,
		ErrorClubActionCreateStream = 15,
		ErrorClubActionEditStream = 16,
		ErrorClubActionDestroyStream = 17,
		ErrorClubActionInviteMember = 18,
		ErrorClubActionEditMember = 19,
		ErrorClubActionEditMemberNote = 20,
		ErrorClubActionKickMember = 21,
		ErrorClubActionAddBan = 22,
		ErrorClubActionRemoveBan = 23,
		ErrorClubActionCreateMessage = 24,
		ErrorClubActionEditMessage = 25,
		ErrorClubActionDestroyMessage = 26,
	},
	---@enum ClubErrorType
	ClubErrorType = {
		ErrorCommunitiesNone = 0,
		ErrorCommunitiesUnknown = 1,
		ErrorCommunitiesNeutralFaction = 2,
		ErrorCommunitiesUnknownRealm = 3,
		ErrorCommunitiesBadTarget = 4,
		ErrorCommunitiesWrongFaction = 5,
		ErrorCommunitiesRestricted = 6,
		ErrorCommunitiesIgnored = 7,
		ErrorCommunitiesGuild = 8,
		ErrorCommunitiesWrongRegion = 9,
		ErrorCommunitiesUnknownTicket = 10,
		ErrorCommunitiesMissingShortName = 11,
		ErrorCommunitiesProfanity = 12,
		ErrorCommunitiesTrial = 13,
		ErrorCommunitiesVeteranTrial = 14,
		ErrorCommunitiesChatMute = 15,
		ErrorClubFull = 16,
		ErrorClubNoClub = 17,
		ErrorClubNotMember = 18,
		ErrorClubAlreadyMember = 19,
		ErrorClubNoSuchMember = 20,
		ErrorClubNoSuchInvitation = 21,
		ErrorClubInvitationAlreadyExists = 22,
		ErrorClubInvalidRoleID = 23,
		ErrorClubInsufficientPrivileges = 24,
		ErrorClubTooManyClubsJoined = 25,
		ErrorClubVoiceFull = 26,
		ErrorClubStreamNoStream = 27,
		ErrorClubStreamInvalidName = 28,
		ErrorClubStreamCountAtMin = 29,
		ErrorClubStreamCountAtMax = 30,
		ErrorClubMemberHasRequiredRole = 31,
		ErrorClubSentInvitationCountAtMax = 32,
		ErrorClubReceivedInvitationCountAtMax = 33,
		ErrorClubTargetIsBanned = 34,
		ErrorClubBanAlreadyExists = 35,
		ErrorClubBanCountAtMax = 36,
		ErrorClubTicketCountAtMax = 37,
		ErrorClubTicketNoSuchTicket = 38,
		ErrorClubTicketHasConsumedAllowedRedeemCount = 39,
		ErrorClubDoesntAllowCrossFaction = 40,
		ErrorClubEditHasCrossFactionMembers = 41,
	},
	---@enum ClubFieldType
	ClubFieldType = {
		ClubName = 0,
		ClubShortName = 1,
		ClubDescription = 2,
		ClubBroadcast = 3,
		ClubStreamName = 4,
		ClubStreamSubject = 5,
		NumTypes = 6,
	},
	---@enum ClubFinderApplicationUpdateType
	ClubFinderApplicationUpdateType = {
		None = 0,
		AcceptInvite = 1,
		DeclineInvite = 2,
		Cancel = 3,
	},
	---@enum ClubFinderClubPostingStatusFlags
	ClubFinderClubPostingStatusFlags = {
		None = 0,
		NeedsCacheUpdate = 1,
		ForceDescriptionChange = 2,
		ForceNameChange = 3,
		UnderReview = 4,
		Banned = 5,
		FakePost = 6,
		PendingDelete = 7,
		PostDelisted = 8,
	},
	---@enum ClubFinderDisableReason
	ClubFinderDisableReason = {
		Muted = 0,
		Silenced = 1,
		VeteranTrial = 2,
	},
	---@enum ClubFinderPostingReportType
	ClubFinderPostingReportType = {
		PostersName = 0,
		ClubName = 1,
		PostingDescription = 2,
		ApplicantsName = 3,
		JoinNote = 4,
	},
	---@enum ClubFinderRequestType
	ClubFinderRequestType = {
		None = 0,
		Guild = 1,
		Community = 2,
		All = 3,
	},
	---@enum ClubFinderSettingFlags
	ClubFinderSettingFlags = {
		None = 0,
		Dungeons = 1,
		Raids = 2,
		PvP = 3,
		RP = 4,
		Social = 5,
		Small = 6,
		Medium = 7,
		Large = 8,
		Tank = 9,
		Healer = 10,
		Damage = 11,
		EnableListing = 12,
		MaxLevelOnly = 13,
		AutoAccept = 14,
		FactionHorde = 15,
		FactionAlliance = 16,
		FactionNeutral = 17,
		SortRelevance = 18,
		SortMemberCount = 19,
		SortNewest = 20,
		LanguageReserved1 = 21,
		LanguageReserved2 = 22,
		LanguageReserved3 = 23,
		LanguageReserved4 = 24,
		LanguageReserved5 = 25,
	},
	---@enum ClubInvitationCandidateStatus
	ClubInvitationCandidateStatus = {
		Available = 0,
		InvitePending = 1,
		AlreadyMember = 2,
	},
	---@enum ClubMemberPresence
	ClubMemberPresence = {
		Unknown = 0,
		Online = 1,
		OnlineMobile = 2,
		Offline = 3,
		Away = 4,
		Busy = 5,
	},
	---@enum ClubRemovedReason
	ClubRemovedReason = {
		None = 0,
		Banned = 1,
		Removed = 2,
		ClubDestroyed = 3,
	},
	---@enum ClubRestrictionReason
	ClubRestrictionReason = {
		None = 0,
		Unavailable = 1,
	},
	---@enum ClubRoleIdentifier
	ClubRoleIdentifier = {
		Owner = 1,
		Leader = 2,
		Moderator = 3,
		Member = 4,
	},
	---@enum ClubStreamNotificationFilter
	ClubStreamNotificationFilter = {
		None = 0,
		Mention = 1,
		All = 2,
	},
	---@enum ClubStreamType
	ClubStreamType = {
		General = 0,
		Guild = 1,
		Officer = 2,
		Other = 3,
	},
	---@enum ClubType
	ClubType = {
		BattleNet = 0,
		Character = 1,
		Guild = 2,
		Other = 3,
	},
	---@enum CommunicationMode
	CommunicationMode = {
		PushToTalk = 0,
		OpenMic = 1,
	},
	---@enum ConquestProgressBarDisplayType
	ConquestProgressBarDisplayType = {
		FirstChest = 0,
		AdditionalChest = 1,
		Seasonal = 2,
	},
	---@enum ConsoleCategory
	ConsoleCategory = {
		Debug = 0,
		Graphics = 1,
		Console = 2,
		Combat = 3,
		Game = 4,
		Default = 5,
		Net = 6,
		Sound = 7,
		Gm = 8,
		Reveal = 9,
		None = 10,
	},
	---@enum ConsoleColorType
	ConsoleColorType = {
		DefaultColor = 0,
		InputColor = 1,
		EchoColor = 2,
		ErrorColor = 3,
		WarningColor = 4,
		GlobalColor = 5,
		AdminColor = 6,
		HighlightColor = 7,
		BackgroundColor = 8,
		ClickbufferColor = 9,
		PrivateColor = 10,
		DefaultGreen = 11,
	},
	---@enum ConsoleCommandType
	ConsoleCommandType = {
		Cvar = 0,
		Command = 1,
		Macro = 2,
		Script = 3,
	},
	---@enum ContributionAppearanceFlags
	ContributionAppearanceFlags = {
		TooltipUseTimeRemaining = 0,
	},
	---@enum ContributionResult
	ContributionResult = {
		Success = 0,
		MustBeNearNpc = 1,
		IncorrectState = 2,
		InvalidID = 3,
		QuestDataMissing = 4,
		FailedConditionCheck = 5,
		UnableToCompleteTurnIn = 6,
		InternalError = 7,
	},
	---@enum ContributionState
	ContributionState = {
		None = 0,
		Building = 1,
		Active = 2,
		UnderAttack = 3,
		Destroyed = 4,
	},
	---@enum CovenantAbilityType
	CovenantAbilityType = {
		Class = 0,
		Signature = 1,
		Soulbind = 2,
	},
	---@enum CovenantSkill
	CovenantSkill = {
		Kyrian = 2730,
		Venthyr = 2731,
		NightFae = 2732,
		Necrolord = 2733,
	},
	---@enum CovenantType
	CovenantType = {
		None = 0,
		Kyrian = 1,
		Venthyr = 2,
		NightFae = 3,
		Necrolord = 4,
	},
	---@enum CurrencyDestroyReason
	CurrencyDestroyReason = {
		Cheat = 0,
		Spell = 1,
		VersionUpdate = 2,
		QuestTurnin = 3,
		Vendor = 4,
		Trade = 5,
		Capped = 6,
		Garrison = 7,
		DroppedToCorpse = 8,
		BonusRoll = 9,
		FactionConversion = 10,
		Last = 11,
	},
	---@enum CurrencyFlags
	CurrencyFlags = {
		CurrencyTradable = 1,
		CurrencyAppearsInLootWindow = 2,
		CurrencyComputedWeeklyMaximum = 4,
		Currency_100_Scaler = 8,
		CurrencyNoLowLevelDrop = 16,
		CurrencyIgnoreMaxQtyOnLoad = 32,
		CurrencyLogOnWorldChange = 64,
		CurrencyTrackQuantity = 128,
		CurrencyResetTrackedQuantity = 256,
		CurrencyUpdateVersionIgnoreMax = 512,
		CurrencySuppressChatMessageOnVersionChange = 1024,
		CurrencySingleDropInLoot = 2048,
		CurrencyHasWeeklyCatchup = 4096,
		CurrencyDoNotCompressChat = 8192,
		CurrencyDoNotLogAcquisitionToBi = 16384,
		CurrencyNoRaidDrop = 32768,
		CurrencyNotPersistent = 65536,
		CurrencyDeprecated = 131072,
		CurrencyDynamicMaximum = 262144,
		CurrencySuppressChatMessages = 524288,
		CurrencyDoNotToast = 1048576,
		CurrencyDestroyExtraOnLoot = 2097152,
		CurrencyDontShowTotalInTooltip = 4194304,
		CurrencyDontCoalesceInLootWindow = 8388608,
		CurrencyAccountWide = 16777216,
		CurrencyAllowOverflowMailer = 33554432,
		CurrencyHideAsReward = 67108864,
		CurrencyHasWarmodeBonus = 134217728,
		CurrencyIsAllianceOnly = 268435456,
		CurrencyIsHordeOnly = 536870912,
		CurrencyLimitWarmodeBonusOncePerTooltip = 1073741824,
		DeprecatedCurrencyFlag = 2147483648,
	},
	---@enum CurrencyFlagsB
	CurrencyFlagsB = {
		CurrencyBUseTotalEarnedForEarned = 1,
		CurrencyBShowQuestXPGainInTooltip = 2,
		CurrencyBNoNotificationMailOnOfflineProgress = 4,
	},
	---@enum CurrencyGainFlags
	CurrencyGainFlags = {
		BonusAward = 1,
		DroppedFromDeath = 2,
		FromAccountServer = 4,
	},
	---@enum CurrencySource
	CurrencySource = {
		ConvertOldItem = 0,
		ConvertOldPvPCurrency = 1,
		ItemRefund = 2,
		QuestReward = 3,
		Cheat = 4,
		Vendor = 5,
		PvPKillCredit = 6,
		PvPMetaCredit = 7,
		PvPScriptedAward = 8,
		Loot = 9,
		UpdatingVersion = 10,
		LFGReward = 11,
		Trade = 12,
		Spell = 13,
		ItemDeletion = 14,
		RatedBattleground = 15,
		RandomBattleground = 16,
		Arena = 17,
		ExceededMaxQty = 18,
		PvPCompletionBonus = 19,
		Script = 20,
		GuildBankWithdrawal = 21,
		Pushloot = 22,
		GarrisonBuilding = 23,
		PvPDrop = 24,
		GarrisonFollowerActivation = 25,
		GarrisonBuildingRefund = 26,
		GarrisonMissionReward = 27,
		GarrisonResourceOverTime = 28,
		QuestRewardIgnoreCaps = 29,
		GarrisonTalent = 30,
		GarrisonWorldQuestBonus = 31,
		PvPHonorReward = 32,
		BonusRoll = 33,
		AzeriteRespec = 34,
		WorldQuestReward = 35,
		WorldQuestRewardIgnoreCaps = 36,
		FactionConversion = 37,
		DailyQuestReward = 38,
		DailyQuestWarModeReward = 39,
		WeeklyQuestReward = 40,
		WeeklyQuestWarModeReward = 41,
		AccountCopy = 42,
		WeeklyRewardChest = 43,
		GarrisonTalentTreeReset = 44,
		DailyReset = 45,
		AddConduitToCollection = 46,
		Barbershop = 47,
		ConvertItemsToCurrencyValue = 48,
		PvPTeamContribution = 49,
		Transmogrify = 50,
		AuctionDeposit = 51,
		Last = 52,
	},
	---@enum CurrencyTokenCategoryFlags
	CurrencyTokenCategoryFlags = {
		FlagSortLast = 1,
		FlagPlayerItemAssignment = 2,
		Hidden = 4,
		Virtual = 8,
	},
	---@enum CustomBindingType
	CustomBindingType = {
		VoicePushToTalk = 0,
	},
	---@enum Damageclass
	Damageclass = {
		MaskNone = 0,
		Physical = 0,
		AllPhysical = 1,
		Holy = 1,
		MaskPhysical = 1,
		Fire = 2,
		FirstResist = 2,
		MaskHoly = 2,
		MaskHolystrike = 3,
		Nature = 3,
		Frost = 4,
		MaskFire = 4,
		MaskFlamestrike = 5,
		Shadow = 5,
		Arcane = 6,
		LastResist = 6,
		MaskHolyfire = 6,
		NumClasses = 7,
		MaskNature = 8,
		MaskStormstrike = 9,
		MaskHolystorm = 10,
		MaskFirestorm = 12,
		MaskFrost = 16,
		MaskFroststrike = 17,
		MaskHolyfrost = 18,
		MaskFrostfire = 20,
		MaskFroststorm = 24,
		MaskElemental = 28,
		MaskShadow = 32,
		MaskShadowstrike = 33,
		MaskTwilight = 34,
		MaskShadowflame = 36,
		MaskShadowstorm = 40,
		MaskShadowfrost = 48,
		MaskChromatic = 62,
		MaskArcane = 64,
		MaskSpellstrike = 65,
		MaskDivine = 66,
		MaskSpellfire = 68,
		MaskSpellstorm = 72,
		MaskSpellfrost = 80,
		MaskSpellshadow = 96,
		MaskCosmic = 106,
		MaskChaos = 124,
		AllMagical = 126,
		MaskMagical = 126,
		All = 127,
	},
	---@enum DamageclassType
	DamageclassType = {
		Physical = 0,
		Magical = 1,
	},
	---@enum EnvironmentalDamageFlags
	EnvironmentalDamageFlags = {
		OneTime = 1,
		DmgIsPct = 2,
	},
	---@enum Environmentaldamagetype
	Environmentaldamagetype = {
		Fatigue = 0,
		Drowning = 1,
		Falling = 2,
		Lava = 3,
		Slime = 4,
		Fire = 5,
	},
	---@enum EventToastDisplayType
	EventToastDisplayType = {
		NormalSingleLine = 0,
		NormalBlockText = 1,
		NormalTitleAndSubTitle = 2,
		NormalTextWithIcon = 3,
		LargeTextWithIcon = 4,
		NormalTextWithIconAndRarity = 5,
		Scenario = 6,
		ChallengeMode = 7,
		ScenarioClickExpand = 8,
	},
	---@enum EventToastEventType
	EventToastEventType = {
		LevelUp = 0,
		LevelUpSpell = 1,
		LevelUpDungeon = 2,
		LevelUpRaid = 3,
		LevelUpPvP = 4,
		PetBattleNewAbility = 5,
		PetBattleFinalRound = 6,
		PetBattleCapture = 7,
		BattlePetLevelChanged = 8,
		BattlePetLevelUpAbility = 9,
		QuestBossEmote = 10,
		MythicPlusWeeklyRecord = 11,
		QuestTurnedIn = 12,
		WorldStateChange = 13,
		Scenario = 14,
		LevelUpOther = 15,
		PlayerAuraAdded = 16,
		PlayerAuraRemoved = 17,
		SpellScript = 18,
		CriteriaUpdated = 19,
		PvPTierUpdate = 20,
	},
	---@enum FlightPathFaction
	FlightPathFaction = {
		Neutral = 0,
		Horde = 1,
		Alliance = 2,
	},
	---@enum FlightPathState
	FlightPathState = {
		Current = 0,
		Reachable = 1,
		Unreachable = 2,
	},
	---@enum FollowerAbilityCastResult
	FollowerAbilityCastResult = {
		Success = 0,
		Failure = 1,
		NoPendingCast = 2,
		InvalidTarget = 3,
		InvalidFollowerSpell = 4,
		RerollNotAllowed = 5,
		SingleMissionDuration = 6,
		MustTargetFollower = 7,
		MustTargetTrait = 8,
		InvalidFollowerType = 9,
		MustBeUnique = 10,
		CannotTargetLimitedUseFollower = 11,
		MustTargetLimitedUseFollower = 12,
		AlreadyAtMaxDurability = 13,
		CannotTargetNonAutoMissionFollower = 14,
	},
	---@enum GamePadPowerLevel
	GamePadPowerLevel = {
		Critical = 0,
		Low = 1,
		Medium = 2,
		High = 3,
		Wired = 4,
		Unknown = 5,
	},
	---@enum GarrAutoBoardIndex
	GarrAutoBoardIndex = {
		None = -1,
		AllyLeftBack = 0,
		AllyRightBack = 1,
		AllyLeftFront = 2,
		AllyCenterFront = 3,
		AllyRightFront = 4,
		EnemyLeftFront = 5,
		EnemyCenterLeftFront = 6,
		EnemyCenterRightFront = 7,
		EnemyRightFront = 8,
		EnemyLeftBack = 9,
		EnemyCenterLeftBack = 10,
		EnemyCenterRightBack = 11,
		EnemyRightBack = 12,
	},
	---@enum GarrAutoCombatSpellTutorialFlag
	GarrAutoCombatSpellTutorialFlag = {
		None = 0,
		Single = 1,
		Column = 2,
		Row = 3,
		All = 4,
	},
	---@enum GarrAutoCombatTutorial
	GarrAutoCombatTutorial = {
		SelectMission = 1,
		PlaceCompanion = 2,
		HealCompanion = 4,
		LevelHeal = 8,
		BeneficialEffect = 16,
		AttackSingle = 32,
		AttackColumn = 64,
		AttackRow = 128,
		AttackAll = 256,
		TroopTutorial = 512,
		EnvironmentalEffect = 1024,
	},
	---@enum GarrAutoCombatantRole
	GarrAutoCombatantRole = {
		None = 0,
		Melee = 1,
		RangedPhysical = 2,
		RangedMagic = 3,
		HealSupport = 4,
		Tank = 5,
	},
	---@enum GarrAutoEventFlags
	GarrAutoEventFlags = {
		None = 0,
		AutoAttack = 1,
		Passive = 2,
		Environment = 4,
	},
	---@enum GarrAutoMissionEventType
	GarrAutoMissionEventType = {
		MeleeDamage = 0,
		RangeDamage = 1,
		SpellMeleeDamage = 2,
		SpellRangeDamage = 3,
		Heal = 4,
		PeriodicDamage = 5,
		PeriodicHeal = 6,
		ApplyAura = 7,
		RemoveAura = 8,
		Died = 9,
	},
	---@enum GarrAutoPreviewTargetType
	GarrAutoPreviewTargetType = {
		None = 0,
		Damage = 1,
		Heal = 2,
		Buff = 4,
		Debuff = 8,
	},
	---@enum GarrFollowerMissionCompleteState
	GarrFollowerMissionCompleteState = {
		Alive = 0,
		KilledByMissionFailure = 1,
		SavedByPreventDeath = 2,
		OutOfDurability = 3,
	},
	---@enum GarrFollowerQuality
	GarrFollowerQuality = {
		None = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
		Title = 6,
	},
	---@enum GarrTalentCostType
	GarrTalentCostType = {
		Initial = 0,
		Respec = 1,
		MakePermanent = 2,
		TreeReset = 3,
	},
	---@enum GarrTalentFeatureSubtype
	GarrTalentFeatureSubtype = {
		Generic = 0,
		Bastion = 1,
		Revendreth = 2,
		Ardenweald = 3,
		Maldraxxus = 4,
	},
	---@enum GarrTalentFeatureType
	GarrTalentFeatureType = {
		Generic = 0,
		AnimaDiversion = 1,
		TravelPortals = 2,
		Adventures = 3,
		ReservoirUpgrades = 4,
		SanctumUnique = 5,
		SoulBinds = 6,
		AnimaDiversionMap = 7,
		Cyphers = 8,
	},
	---@enum GarrTalentResearchCostSource
	GarrTalentResearchCostSource = {
		Talent = 0,
		Tree = 1,
	},
	---@enum GarrTalentSocketType
	GarrTalentSocketType = {
		None = 0,
		Spell = 1,
		Conduit = 2,
	},
	---@enum GarrTalentTreeType
	GarrTalentTreeType = {
		Tiers = 0,
		Classic = 1,
	},
	---@enum GarrTalentType
	GarrTalentType = {
		Standard = 0,
		Minor = 1,
		Major = 2,
		Socket = 3,
	},
	---@enum GarrTalentUI
	GarrTalentUI = {
		Generic = 0,
		CovenantSanctum = 1,
		SoulBinds = 2,
		AnimaDiversionMap = 3,
	},
	---@enum GarrisonFollowerType
	GarrisonFollowerType = {
		FollowerType_6_0 = 1,
		FollowerType_6_2 = 2,
		FollowerType_7_0 = 4,
		FollowerType_8_0 = 22,
		FollowerType_9_0 = 123,
	},
	---@enum GarrisonTalentAvailability
	GarrisonTalentAvailability = {
		Available = 0,
		Unavailable = 1,
		UnavailableAnotherIsResearching = 2,
		UnavailableNotEnoughResources = 3,
		UnavailableNotEnoughGold = 4,
		UnavailableTierUnavailable = 5,
		UnavailablePlayerCondition = 6,
		UnavailableAlreadyHave = 7,
		UnavailableRequiresPrerequisiteTalent = 8,
	},
	---@enum GarrisonType
	GarrisonType = {
		Type_6_0 = 2,
		Type_7_0 = 3,
		Type_8_0 = 9,
		Type_9_0 = 111,
	},
	---@enum GossipOptionRewardType
	GossipOptionRewardType = {
		Item = 0,
		Currency = 1,
	},
	---@enum GossipOptionStatus
	GossipOptionStatus = {
		Available = 0,
		Unavailable = 1,
		Locked = 2,
		AlreadyComplete = 3,
	},
	---@enum HolidayCalendarFlags
	HolidayCalendarFlags = {
		Alliance = 1,
		Horde = 2,
	},
	---@enum HolidayFlags
	HolidayFlags = {
		IsRegionwide = 1,
		DontShowInCalendar = 2,
		DontDisplayEnd = 4,
		DontDisplayBanner = 8,
		NotAvailableClientSide = 16,
	},
	---@enum IconAndTextWidgetState
	IconAndTextWidgetState = {
		Hidden = 0,
		Shown = 1,
		ShownWithDynamicIconFlashing = 2,
		ShownWithDynamicIconNotFlashing = 3,
	},
	---@enum IconState
	IconState = {
		Hidden = 0,
		ShowState1 = 1,
		ShowState2 = 2,
	},
	---@enum InputContext
	InputContext = {
		None = 0,
		Keyboard = 1,
		Mouse = 2,
		GamePad = 3,
	},
	---@enum InventoryType
	InventoryType = {
		IndexNonEquipType = 0,
		IndexHeadType = 1,
		IndexNeckType = 2,
		IndexShoulderType = 3,
		IndexBodyType = 4,
		IndexChestType = 5,
		IndexWaistType = 6,
		IndexLegsType = 7,
		IndexFeetType = 8,
		IndexWristType = 9,
		IndexHandType = 10,
		IndexFingerType = 11,
		IndexTrinketType = 12,
		IndexWeaponType = 13,
		IndexShieldType = 14,
		IndexRangedType = 15,
		IndexCloakType = 16,
		Index2HweaponType = 17,
		IndexBagType = 18,
		IndexTabardType = 19,
		IndexRobeType = 20,
		IndexWeaponmainhandType = 21,
		IndexWeaponoffhandType = 22,
		IndexHoldableType = 23,
		IndexAmmoType = 24,
		IndexThrownType = 25,
		IndexRangedrightType = 26,
		IndexQuiverType = 27,
		IndexRelicType = 28,
	},
	---@enum ItemArmorSubclass
	ItemArmorSubclass = {
		Generic = 0,
		Cloth = 1,
		Leather = 2,
		Mail = 3,
		Plate = 4,
		Cosmetic = 5,
		Shield = 6,
		Libram = 7,
		Idol = 8,
		Totem = 9,
		Sigil = 10,
		Relic = 11,
	},
	---@enum ItemClass
	ItemClass = {
		Consumable = 0,
		Container = 1,
		Weapon = 2,
		Gem = 3,
		Armor = 4,
		Reagent = 5,
		Projectile = 6,
		Tradegoods = 7,
		ItemEnhancement = 8,
		Recipe = 9,
		CurrencyTokenObsolete = 10,
		Quiver = 11,
		Questitem = 12,
		Key = 13,
		PermanentObsolete = 14,
		Miscellaneous = 15,
		Glyph = 16,
		Battlepet = 17,
		WoWToken = 18,
	},
	---@enum ItemCommodityStatus
	ItemCommodityStatus = {
		Unknown = 0,
		Item = 1,
		Commodity = 2,
	},
	---@enum ItemConsumableSubclass
	ItemConsumableSubclass = {
		Generic = 0,
		Potion = 1,
		Elixir = 2,
		Scroll = 3,
		Fooddrink = 4,
		Itemenhancement = 5,
		Bandage = 6,
		Other = 7,
	},
	---@enum ItemCreationContext
	ItemCreationContext = {
		None = 0,
		DungeonNormal = 1,
		DungeonHeroic = 2,
		RaidNormal = 3,
		RaidFinder = 4,
		RaidHeroic = 5,
		RaidMythic = 6,
		PvPUnranked_1 = 7,
		PvPRanked_1 = 8,
		ScenarioNormal = 9,
		ScenarioHeroic = 10,
		QuestReward = 11,
		Store = 12,
		TradeSkill = 13,
		Vendor = 14,
		BlackMarket = 15,
		ChallengeMode_1 = 16,
		DungeonLevelUp_1 = 17,
		DungeonLevelUp_2 = 18,
		DungeonLevelUp_3 = 19,
		DungeonLevelUp_4 = 20,
		ForceNone = 21,
		Timewalker = 22,
		DungeonMythic = 23,
		PvPHonorReward = 24,
		WorldQuest_1 = 25,
		WorldQuest_2 = 26,
		WorldQuest_3 = 27,
		WorldQuest_4 = 28,
		WorldQuest_5 = 29,
		WorldQuest_6 = 30,
		MissionReward_1 = 31,
		MissionReward_2 = 32,
		ChallengeMode_2 = 33,
		ChallengeMode_3 = 34,
		ChallengeModeJackpot = 35,
		WorldQuest_7 = 36,
		WorldQuest_8 = 37,
		PvPRanked_2 = 38,
		PvPRanked_3 = 39,
		PvPRanked_4 = 40,
		PvPUnranked_2 = 41,
		WorldQuest_9 = 42,
		WorldQuest_10 = 43,
		PvPRanked_5 = 44,
		PvPRanked_6 = 45,
		PvPRanked_7 = 46,
		PvPUnranked_3 = 47,
		PvPUnranked_4 = 48,
		PvPUnranked_5 = 49,
		PvPUnranked_6 = 50,
		PvPUnranked_7 = 51,
		PvPRanked_8 = 52,
		WorldQuest_11 = 53,
		WorldQuest_12 = 54,
		WorldQuest_13 = 55,
		PvPRankedJackpot = 56,
		TournamentRealm = 57,
		Relinquished = 58,
		LegendaryForge = 59,
		QuestBonusLoot = 60,
		CharacterBoost_1 = 61,
		CharacterBoost_2 = 62,
		LegendaryCrafting_1 = 63,
		LegendaryCrafting_2 = 64,
		LegendaryCrafting_3 = 65,
		LegendaryCrafting_4 = 66,
		LegendaryCrafting_5 = 67,
		LegendaryCrafting_6 = 68,
		LegendaryCrafting_7 = 69,
		LegendaryCrafting_8 = 70,
		LegendaryCrafting_9 = 71,
		WeeklyRewardsAdditional = 72,
		WeeklyRewardsConcession = 73,
		WorldQuestJackpot = 74,
		NewCharacter = 75,
		WarMode = 76,
		PvPBrawl_1 = 77,
		PvPBrawl_2 = 78,
		Torghast = 79,
		CorpseRecovery = 80,
		WorldBoss = 81,
		RaidNormalExtended = 82,
		RaidFinderExtended = 83,
		RaidHeroicExtended = 84,
		RaidMythicExtended = 85,
		CharacterBoost_3 = 86,
		ChallengeMode_4 = 87,
		PvPRanked_9 = 88,
		RaidNormalExtended_2 = 89,
		RaidFinderExtended_2 = 90,
		RaidHeroicExtended_2 = 91,
		RaidMythicExtended_2 = 92,
		RaidNormalExtended_3 = 93,
		RaidFinderExtended_3 = 94,
		RaidHeroicExtended_3 = 95,
		RaidMythicExtended_3 = 96,
	},
	---@enum ItemGemSubclass
	ItemGemSubclass = {
		Intellect = 0,
		Agility = 1,
		Strength = 2,
		Stamina = 3,
		Spirit = 4,
		Criticalstrike = 5,
		Mastery = 6,
		Haste = 7,
		Versatility = 8,
		Other = 9,
		Multiplestats = 10,
		Artifactrelic = 11,
	},
	---@enum ItemMiscellaneousSubclass
	ItemMiscellaneousSubclass = {
		Junk = 0,
		Reagent = 1,
		CompanionPet = 2,
		Holiday = 3,
		Other = 4,
		Mount = 5,
		MountEquipment = 6,
	},
	---@enum ItemModification
	ItemModification = {
		TransmogrifyItemModifiedAppearanceIDSpecAll = 0,
		TransmogrifyItemModifiedAppearanceIDSpec_0 = 1,
		IncrementLevelObsolete = 2,
		BattlePetSpecies = 3,
		BattlePetBreed = 4,
		BattlePetLevel = 5,
		BattlePetCreaturedisplayid = 6,
		TransmogrifyOverrideEnchantVisualIDSpecAll = 7,
		ArtifactAppearanceID = 8,
		TimewalkerLevel = 9,
		TransmogrifyOverrideEnchantVisualIDSpec_0 = 10,
		TransmogrifyItemModifiedAppearanceIDSpec_1 = 11,
		TransmogrifyOverrideEnchantVisualIDSpec_1 = 12,
		TransmogrifyItemModifiedAppearanceIDSpec_2 = 13,
		TransmogrifyOverrideEnchantVisualIDSpec_2 = 14,
		TransmogrifyItemModifiedAppearanceIDSpec_3 = 15,
		TransmogrifyOverrideEnchantVisualIDSpec_3 = 16,
		KeystoneMapChallengeModeID = 17,
		KeystonePowerLevel = 18,
		KeystoneAffix0 = 19,
		KeystoneAffix01 = 20,
		KeystoneAffix02 = 21,
		KeystoneAffix03 = 22,
		LegionArtifactKnowledgeObsolete = 23,
		ArtifactTier = 24,
		TransmogrifyItemModifiedAppearanceIDSpec_4 = 25,
		PvPRating = 26,
		TransmogrifyOverrideEnchantVisualIDSpec_4 = 27,
		ContentTuningID = 28,
		ChangeModifiedCraftingStat_1 = 29,
		ChangeModifiedCraftingStat_2 = 30,
		TransmogrifySecondaryItemModifiedAppearanceIDSpecAll = 31,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_0 = 32,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_1 = 33,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_2 = 34,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_3 = 35,
		TransmogrifySecondaryItemModifiedAppearanceIDSpec_4 = 36,
		SoulbindConduitRank = 37,
	},
	---@enum ItemQuality
	ItemQuality = {
		Poor = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
		Artifact = 6,
		Heirloom = 7,
		WoWToken = 8,
	},
	---@enum ItemReagentSubclass
	ItemReagentSubclass = {
		Reagent = 0,
		Keystone = 1,
		ContextToken = 2,
	},
	---@enum ItemRecipeSubclass
	ItemRecipeSubclass = {
		Book = 0,
		Leatherworking = 1,
		Tailoring = 2,
		Engineering = 3,
		Blacksmithing = 4,
		Cooking = 5,
		Alchemy = 6,
		FirstAid = 7,
		Enchanting = 8,
		Fishing = 9,
		Jewelcrafting = 10,
		Inscription = 11,
	},
	---@enum ItemSlotFilterType
	ItemSlotFilterType = {
		Head = 0,
		Neck = 1,
		Shoulder = 2,
		Cloak = 3,
		Chest = 4,
		Wrist = 5,
		Hand = 6,
		Waist = 7,
		Legs = 8,
		Feet = 9,
		MainHand = 10,
		OffHand = 11,
		Finger = 12,
		Trinket = 13,
		Other = 14,
		NoFilter = 15,
	},
	---@enum ItemTryOnReason
	ItemTryOnReason = {
		Success = 0,
		WrongRace = 1,
		NotEquippable = 2,
		DataPending = 3,
	},
	---@enum ItemWeaponSubclass
	ItemWeaponSubclass = {
		Axe1H = 0,
		Axe2H = 1,
		Bows = 2,
		Guns = 3,
		Mace1H = 4,
		Mace2H = 5,
		Polearm = 6,
		Sword1H = 7,
		Sword2H = 8,
		Warglaive = 9,
		Staff = 10,
		Bearclaw = 11,
		Catclaw = 12,
		Unarmed = 13,
		Generic = 14,
		Dagger = 15,
		Thrown = 16,
		Obsolete3 = 17,
		Crossbow = 18,
		Wand = 19,
		Fishingpole = 20,
	},
	---@enum Itemclassfilterflags
	Itemclassfilterflags = {
		Consumable = 1,
		Container = 2,
		Weapon = 4,
		Gem = 8,
		Armor = 16,
		Reagent = 32,
		Projectile = 64,
		Tradegoods = 128,
		ItemEnhancement = 256,
		Recipe = 512,
		CurrencyTokenObsolete = 1024,
		Quiver = 2048,
		Questitemclassfilterflags = 4096,
		Key = 8192,
		PermanentObsolete = 16384,
		Miscellaneous = 32768,
		Glyph = 65536,
		Battlepet = 131072,
	},
	---@enum Itemsetflags
	Itemsetflags = {
		Legacy = 1,
		UseItemHistorySetSlots = 2,
		RequiresPvPTalentsActive = 4,
	},
	---@enum JailersTowerType
	JailersTowerType = {
		TwistingCorridors = 0,
		SkoldusHalls = 1,
		FractureChambers = 2,
		Soulforges = 3,
		Coldheart = 4,
		Mortregar = 5,
		UpperReaches = 6,
		ArkobanHall = 7,
		TormentChamberJaina = 8,
		TormentChamberThrall = 9,
		TormentChamberAnduin = 10,
		AdamantVaults = 11,
		ForgottenCatacombs = 12,
		Ossuary = 13,
		BossRush = 14,
	},
	---@enum LFGEntryPlaystyle
	LFGEntryPlaystyle = {
		None = 0,
		Standard = 1,
		Casual = 2,
		Hardcore = 3,
	},
	---@enum LFGListDisplayType
	LFGListDisplayType = {
		RoleCount = 0,
		RoleEnumerate = 1,
		ClassEnumerate = 2,
		HideAll = 3,
		PlayerCount = 4,
	},
	---@enum LFGListFilter
	LFGListFilter = {
		Recommended = 1,
		NotRecommended = 2,
		PvE = 4,
		PvP = 8,
	},
	---@enum LanguageFlag
	LanguageFlag = {
		IsExotic = 1,
		HiddenFromPlayer = 2,
	},
	---@enum LinkedCurrencyFlags
	LinkedCurrencyFlags = {
		IgnoreAdd = 1,
		IgnoreSubtract = 2,
		SuppressChatLog = 4,
	},
	---@enum ManipulatorEventType
	ManipulatorEventType = {
		Start = 0,
		Move = 1,
		Complete = 2,
		Delete = 3,
	},
	---@enum MapCanvasPosition
	MapCanvasPosition = {
		None = 0,
		BottomLeft = 1,
		BottomRight = 2,
		TopLeft = 3,
		TopRight = 4,
	},
	---@enum MapOverlayDisplayLocation
	MapOverlayDisplayLocation = {
		Default = 0,
		BottomLeft = 1,
		TopLeft = 2,
		BottomRight = 3,
		TopRight = 4,
		Hidden = 5,
	},
	---@enum ModelSceneSetting
	ModelSceneSetting = {
		AlignLightToOrbitDelta = 1,
	},
	---@enum ModelSceneType
	ModelSceneType = {
		MountJournal = 0,
		PetJournalCard = 1,
		ShopCard = 2,
		EncounterJournal = 3,
		PetJournalLoadout = 4,
		ArtifactTier2 = 5,
		ArtifactTier2ForgingScene = 6,
		ArtifactTier2SlamEffect = 7,
		CommentatorVictoryFanfare = 8,
		ArtifactRelicTalentEffect = 9,
		PvPWarModeOrb = 10,
		PvPWarModeFire = 11,
		PartyPose = 12,
		AzeriteItemLevelUpToast = 13,
		AzeritePowers = 14,
		AzeriteRewardGlow = 15,
		HeartOfAzeroth = 16,
		WorldMapThreat = 17,
		Soulbinds = 18,
		JailersTowerAnimaGlow = 19,
	},
	---@enum MountType
	MountType = {
		Ground = 0,
		Flying = 1,
		Aquatic = 2,
	},
	---@enum MountTypeFlag
	MountTypeFlag = {
		IsFlyingMount = 1,
		IsAquaticMount = 2,
	},
	---@enum NavigationState
	NavigationState = {
		Invalid = 0,
		Occluded = 1,
		InRange = 2,
	},
	---@enum OptionalReagentItemFlag
	OptionalReagentItemFlag = {
		TooltipShowsAsStatModifications = 0,
	},
	---@enum PartyRequestJoinRelation
	PartyRequestJoinRelation = {
		None = 0,
		Friend = 1,
		Guild = 2,
		Club = 3,
		NumPartyRequestJoinRelations = 4,
	},
	---@enum PermanentChatChannelType
	PermanentChatChannelType = {
		None = 0,
		Zone = 1,
		Communities = 2,
		Custom = 3,
	},
	---@enum PetBattleQueueStatus
	PetBattleQueueStatus = {
		None = 0,
		Queued = 1,
		QueuedUpdate = 2,
		AlreadyQueued = 3,
		JoinFailed = 4,
		JoinFailedSlots = 5,
		JoinFailedJournalLock = 6,
		JoinFailedNeutral = 7,
		MatchAccepted = 8,
		MatchDeclined = 9,
		MatchOpponentDeclined = 10,
		ProposalTimedOut = 11,
		Removed = 12,
		RequeuedAfterInternalError = 13,
		RequeuedAfterOpponentRemoved = 14,
		Matchmaking = 15,
		LostConnection = 16,
		Shutdown = 17,
		Suspended = 18,
		Unsuspended = 19,
		InBattle = 20,
		NoBattlingHere = 21,
	},
	---@enum PetJournalError
	PetJournalError = {
		None = 0,
		PetIsDead = 1,
		JournalIsLocked = 2,
		InvalidFaction = 3,
		NoFavoritesToSummon = 4,
		NoValidRandomSummon = 5,
		InvalidCovenant = 6,
	},
	---@enum PetbattleAuraStateFlags
	PetbattleAuraStateFlags = {
		None = 0,
		Infinite = 1,
		Canceled = 2,
		InitDisabled = 4,
		CountdownFirstRound = 8,
		JustApplied = 16,
		RemoveEventHandled = 32,
	},
	---@enum PetbattleCheatFlags
	PetbattleCheatFlags = {
		None = 0,
		AutoPlay = 1,
	},
	---@enum PetbattleEffectFlags
	PetbattleEffectFlags = {
		None = 0,
		InvalidTarget = 1,
		Miss = 2,
		Crit = 4,
		Blocked = 8,
		Dodge = 16,
		Heal = 32,
		Unkillable = 64,
		Reflect = 128,
		Absorb = 256,
		Immune = 512,
		Strong = 1024,
		Weak = 2048,
		SuccessChain = 4096,
		AuraReapply = 8192,
	},
	---@enum PetbattleEffectType
	PetbattleEffectType = {
		SetHealth = 0,
		AuraApply = 1,
		AuraCancel = 2,
		AuraChange = 3,
		PetSwap = 4,
		StatusChange = 5,
		SetState = 6,
		SetMaxHealth = 7,
		SetSpeed = 8,
		SetPower = 9,
		TriggerAbility = 10,
		AbilityChange = 11,
		NpcEmote = 12,
		AuraProcessingBegin = 13,
		AuraProcessingEnd = 14,
		ReplacePet = 15,
		OverrideAbility = 16,
		WorldStateUpdate = 17,
	},
	---@enum PetbattleEnviros
	PetbattleEnviros = {
		Pad0 = 0,
		Pad1 = 1,
		Weather = 2,
	},
	---@enum PetbattleInputMoveMsgDebugFlag
	PetbattleInputMoveMsgDebugFlag = {
		None = 0,
		DontValidate = 1,
		EnemyCast = 2,
	},
	---@enum PetbattleMoveType
	PetbattleMoveType = {
		Quit = 0,
		Ability = 1,
		Swap = 2,
		Trap = 3,
		FinalRoundOk = 4,
		Pass = 5,
	},
	---@enum PetbattlePboid
	PetbattlePboid = {
		P0Pet_0 = 0,
		P0Pet_1 = 1,
		P0Pet_2 = 2,
		P1Pet_0 = 3,
		P1Pet_1 = 4,
		P1Pet_2 = 5,
		EnvPad_0 = 6,
		EnvPad_1 = 7,
		EnvWeather = 8,
	},
	---@enum PetbattlePetStatus
	PetbattlePetStatus = {
		FlagNone = 0,
		FlagTrapped = 1,
		Stunned = 2,
		SwapOutLocked = 4,
		SwapInLocked = 8,
	},
	---@enum PetbattlePlayer
	PetbattlePlayer = {
		Player_0 = 0,
		Player_1 = 1,
	},
	---@enum PetbattlePlayerInputFlags
	PetbattlePlayerInputFlags = {
		None = 0,
		TurnInProgress = 1,
		AbilityLocked = 2,
		SwapLocked = 4,
		WaitingForPet = 8,
	},
	---@enum PetbattleResult
	PetbattleResult = {
		FailUnknown = 0,
		FailNotHere = 1,
		FailNotHereOnTransport = 2,
		FailNotHereUnevenGround = 3,
		FailNotHereObstructed = 4,
		FailNotWhileInCombat = 5,
		FailNotWhileDead = 6,
		FailNotWhileFlying = 7,
		FailTargetInvalid = 8,
		FailTargetOutOfRange = 9,
		FailTargetNotCapturable = 10,
		FailNotATrainer = 11,
		FailDeclined = 12,
		FailInBattle = 13,
		FailInvalidLoadout = 14,
		FailInvalidLoadoutAllDead = 15,
		FailInvalidLoadoutNoneSlotted = 16,
		FailNoJournalLock = 17,
		FailWildPetTapped = 18,
		FailRestrictedAccount = 19,
		FailOpponentNotAvailable = 20,
		FailLogout = 21,
		FailDisconnect = 22,
		Success = 23,
	},
	---@enum PetbattleSlot
	PetbattleSlot = {
		Slot_0 = 0,
		Slot_1 = 1,
		Slot_2 = 2,
	},
	---@enum PetbattleSlotAbility
	PetbattleSlotAbility = {
		Ability_0 = 0,
		Ability_1 = 1,
		Ability_2 = 2,
	},
	---@enum PetbattleSlotResult
	PetbattleSlotResult = {
		Success = 0,
		SlotLocked = 1,
		SlotEmpty = 2,
		NoTracker = 3,
		NoSpeciesRec = 4,
		CantBattle = 5,
		Revoked = 6,
		Dead = 7,
		NoPet = 8,
	},
	---@enum PetbattleState
	PetbattleState = {
		Created = 0,
		WaitingPreBattle = 1,
		RoundInProgress = 2,
		WaitingForFrontPets = 3,
		CreatedFailed = 4,
		FinalRound = 5,
		Finished = 6,
	},
	---@enum PetbattleTrapstatus
	PetbattleTrapstatus = {
		Invalid = 0,
		CanTrap = 1,
		CantTrapNewbie = 2,
		CantTrapPetDead = 3,
		CantTrapPetHealth = 4,
		CantTrapNoRoomInJournal = 5,
		CantTrapPetNotCapturable = 6,
		CantTrapTrainerBattle = 7,
		CantTrapTwice = 8,
	},
	---@enum PetbattleType
	PetbattleType = {
		PvE = 0,
		PvP = 1,
		Lfpb = 2,
		Npc = 3,
	},
	---@enum PhaseReason
	PhaseReason = {
		Phasing = 0,
		Sharding = 1,
		WarMode = 2,
		ChromieTime = 3,
	},
	---@enum PlayerChoiceRarity
	PlayerChoiceRarity = {
		Common = 0,
		Uncommon = 1,
		Rare = 2,
		Epic = 3,
	},
	---@enum PlayerClubRequestStatus
	PlayerClubRequestStatus = {
		None = 0,
		Pending = 1,
		AutoApproved = 2,
		Declined = 3,
		Approved = 4,
		Joined = 5,
		JoinedAnother = 6,
		Canceled = 7,
	},
	---@enum PlayerCurrencyFlags
	PlayerCurrencyFlags = {
		Incremented = 1,
		Loading = 2,
	},
	---@enum PlayerCurrencyFlagsDbFlags
	PlayerCurrencyFlagsDbFlags = {
		IgnoreMaxQtyOnload = 1,
		Reuse1 = 2,
		InBackpack = 4,
		UnusedInUI = 8,
		Reuse2 = 16,
	},
	---@enum PlayerMentorshipApplicationResult
	PlayerMentorshipApplicationResult = {
		Success = 0,
		AlreadyMentor = 1,
		Ineligible = 2,
	},
	---@enum PlayerMentorshipStatus
	PlayerMentorshipStatus = {
		None = 0,
		Newcomer = 1,
		Mentor = 2,
	},
	---@enum PowerType
	PowerType = {
		HealthCost = -2,
		None = -1,
		Mana = 0,
		Rage = 1,
		Focus = 2,
		Energy = 3,
		ComboPoints = 4,
		Runes = 5,
		RunicPower = 6,
		SoulShards = 7,
		LunarPower = 8,
		HolyPower = 9,
		Alternate = 10,
		Maelstrom = 11,
		Chi = 12,
		Insanity = 13,
		Obsolete = 14,
		Obsolete2 = 15,
		ArcaneCharges = 16,
		Fury = 17,
		Pain = 18,
		NumPowerTypes = 19,
	},
	---@enum PvPFaction
	PvPFaction = {
		Horde = 0,
		Alliance = 1,
	},
	---@enum PvPMatchState
	PvPMatchState = {
		Inactive = 0,
		Active = 1,
		Complete = 2,
	},
	---@enum PvPUnitClassification
	PvPUnitClassification = {
		FlagCarrierHorde = 0,
		FlagCarrierAlliance = 1,
		FlagCarrierNeutral = 2,
		CartRunnerHorde = 3,
		CartRunnerAlliance = 4,
		AssassinHorde = 5,
		AssassinAlliance = 6,
		OrbCarrierBlue = 7,
		OrbCarrierGreen = 8,
		OrbCarrierOrange = 9,
		OrbCarrierPurple = 10,
	},
	---@enum QuestFrequency
	QuestFrequency = {
		Default = 0,
		Daily = 1,
		Weekly = 2,
	},
	---@enum QuestLineFloorLocation
	QuestLineFloorLocation = {
		Above = 0,
		Below = 1,
		Same = 2,
	},
	---@enum QuestPOIQuestTypes
	QuestPOIQuestTypes = {
		Normal = 1,
		Campaign = 2,
		Calling = 3,
	},
	---@enum QuestSessionCommand
	QuestSessionCommand = {
		None = 0,
		Start = 1,
		Stop = 2,
		SessionActiveNoCommand = 3,
	},
	---@enum QuestSessionResult
	QuestSessionResult = {
		Ok = 0,
		NotInParty = 1,
		InvalidOwner = 2,
		AlreadyActive = 3,
		NotActive = 4,
		InRaid = 5,
		OwnerRefused = 6,
		Timeout = 7,
		Disabled = 8,
		Started = 9,
		Stopped = 10,
		Joined = 11,
		Left = 12,
		OwnerLeft = 13,
		ReadyCheckFailed = 14,
		PartyDestroyed = 15,
		MemberTimeout = 16,
		AlreadyMember = 17,
		NotOwner = 18,
		AlreadyOwner = 19,
		AlreadyJoined = 20,
		NotMember = 21,
		Busy = 22,
		JoinRejected = 23,
		Logout = 24,
		Empty = 25,
		QuestNotCompleted = 26,
		Resync = 27,
		Restricted = 28,
		InPetBattle = 29,
		InvalidPublicParty = 30,
		Unknown = 31,
		InCombat = 32,
		MemberInCombat = 33,
		RestrictedCrossFaction = 34,
	},
	---@enum QuestTag
	QuestTag = {
		Group = 1,
		PvP = 41,
		Raid = 62,
		Dungeon = 81,
		Legendary = 83,
		Heroic = 85,
		Raid10 = 88,
		Raid25 = 89,
		Scenario = 98,
		Account = 102,
		CombatAlly = 266,
	},
	---@enum QuestTagType
	QuestTagType = {
		Tag = 0,
		Profession = 1,
		Normal = 2,
		PvP = 3,
		PetBattle = 4,
		Bounty = 5,
		Dungeon = 6,
		Invasion = 7,
		Raid = 8,
		Contribution = 9,
		RatedReward = 10,
		InvasionWrapper = 11,
		FactionAssault = 12,
		Islands = 13,
		Threat = 14,
		CovenantCalling = 15,
	},
	---@enum QuestWatchType
	QuestWatchType = {
		Automatic = 0,
		Manual = 1,
	},
	---@enum RafLinkType
	RafLinkType = {
		None = 0,
		Recruit = 1,
		Friend = 2,
		Both = 3,
	},
	---@enum RafRecruitActivityState
	RafRecruitActivityState = {
		Incomplete = 0,
		Complete = 1,
		RewardClaimed = 2,
	},
	---@enum RafRecruitSubStatus
	RafRecruitSubStatus = {
		Trial = 0,
		Active = 1,
		Inactive = 2,
	},
	---@enum RafRewardType
	RafRewardType = {
		Pet = 0,
		Mount = 1,
		Appearance = 2,
		Title = 3,
		GameTime = 4,
		AppearanceSet = 5,
		Illusion = 6,
		Invalid = 7,
	},
	---@enum RelativeContentDifficulty
	RelativeContentDifficulty = {
		Trivial = 0,
		Easy = 1,
		Fair = 2,
		Difficult = 3,
		Impossible = 4,
	},
	---@enum ReportMajorCategory
	ReportMajorCategory = {
		InappropriateCommunication = 0,
		GameplaySabotage = 1,
		Cheating = 2,
		InappropriateName = 3,
	},
	---@enum ReportMinorCategory
	ReportMinorCategory = {
		TextChat = 1,
		Boosting = 2,
		Spam = 4,
		Afk = 8,
		IntentionallyFeeding = 16,
		BlockingProgress = 32,
		Hacking = 64,
		Botting = 128,
		Advertisement = 256,
		BTag = 512,
		GroupName = 1024,
		CharacterName = 2048,
		GuildName = 4096,
		Description = 8192,
		Name = 16384,
	},
	---@enum ReportType
	ReportType = {
		Chat = 0,
		InWorld = 1,
		ClubFinderPosting = 2,
		ClubFinderApplicant = 3,
		GroupFinderPosting = 4,
		GroupFinderApplicant = 5,
		ClubMember = 6,
		GroupMember = 7,
		Friend = 8,
		Pet = 9,
		BattlePet = 10,
		Calendar = 11,
		Mail = 12,
		PvP = 13,
	},
	---@enum RuneforgePowerFilter
	RuneforgePowerFilter = {
		All = 0,
		Relevant = 1,
		Available = 2,
		Unavailable = 3,
	},
	---@enum RuneforgePowerState
	RuneforgePowerState = {
		Available = 0,
		Unavailable = 1,
		Invalid = 2,
	},
	---@enum ScriptedAnimationBehavior
	ScriptedAnimationBehavior = {
		None = 0,
		TargetShake = 1,
		TargetKnockBack = 2,
		SourceRecoil = 3,
		SourceCollideWithTarget = 4,
		UIParentShake = 5,
	},
	---@enum ScriptedAnimationFlags
	ScriptedAnimationFlags = {
		UseTargetAsSource = 1,
	},
	---@enum ScriptedAnimationTrajectory
	ScriptedAnimationTrajectory = {
		AtSource = 0,
		AtTarget = 1,
		Straight = 2,
		CurveLeft = 3,
		CurveRight = 4,
		CurveRandom = 5,
		HalfwayBetween = 6,
	},
	---@enum SelfResurrectOptionType
	SelfResurrectOptionType = {
		Spell = 0,
		Item = 1,
	},
	---@enum SkinningState
	SkinningState = {
		None = 0,
		Reserved = 1,
		Skinning = 2,
		Looting = 3,
		Skinned = 4,
	},
	---@enum SoulbindConduitFlags
	SoulbindConduitFlags = {
		VisibleToGetallsoulbindconduitScript = 1,
	},
	---@enum SoulbindConduitInstallResult
	SoulbindConduitInstallResult = {
		Success = 0,
		InvalidItem = 1,
		InvalidConduit = 2,
		InvalidTalent = 3,
		DuplicateConduit = 4,
		ForgeNotInProximity = 5,
		SocketNotEmpty = 6,
	},
	---@enum SoulbindConduitTransactionType
	SoulbindConduitTransactionType = {
		Install = 0,
		Uninstall = 1,
	},
	---@enum SoulbindConduitType
	SoulbindConduitType = {
		Finesse = 0,
		Potency = 1,
		Endurance = 2,
		Flex = 3,
	},
	---@enum SoulbindNodeState
	SoulbindNodeState = {
		Unavailable = 0,
		Unselected = 1,
		Selectable = 2,
		Selected = 3,
	},
	---@enum SpellDisplayIconDisplayType
	SpellDisplayIconDisplayType = {
		Buff = 0,
		Debuff = 1,
		Circular = 2,
		NoBorder = 3,
	},
	---@enum SpellDisplayIconSizeType
	SpellDisplayIconSizeType = {
		Small = 0,
		Medium = 1,
		Large = 2,
	},
	---@enum SpellDisplayTextShownStateType
	SpellDisplayTextShownStateType = {
		Shown = 0,
		Hidden = 1,
	},
	---@enum SplashScreenType
	SplashScreenType = {
		WhatsNew = 0,
		SeasonRollOver = 1,
	},
	---@enum StatusBarColorTintValue
	StatusBarColorTintValue = {
		None = 0,
		Black = 1,
		White = 2,
		Red = 3,
		Yellow = 4,
		Orange = 5,
		Purple = 6,
		Green = 7,
		Blue = 8,
	},
	---@enum StatusBarOverrideBarTextShownType
	StatusBarOverrideBarTextShownType = {
		Never = 0,
		Always = 1,
		OnlyOnMouseover = 2,
		OnlyNotOnMouseover = 3,
	},
	---@enum StatusBarValueTextType
	StatusBarValueTextType = {
		Hidden = 0,
		Percentage = 1,
		Value = 2,
		Time = 3,
		TimeShowOneLevelOnly = 4,
		ValueOverMax = 5,
		ValueOverMaxNormalized = 6,
	},
	---@enum SubscriptionInterstitialResponseType
	SubscriptionInterstitialResponseType = {
		Clicked = 0,
		Closed = 1,
		WebRedirect = 2,
	},
	---@enum SubscriptionInterstitialType
	SubscriptionInterstitialType = {
		Standard = 0,
		LeftNpeArea = 1,
		MaxLevel = 2,
	},
	---@enum SummonStatus
	SummonStatus = {
		None = 0,
		Pending = 1,
		Accepted = 2,
		Declined = 3,
	},
	---@enum SuperTrackingType
	SuperTrackingType = {
		Quest = 0,
		UserWaypoint = 1,
		Corpse = 2,
		Scenario = 3,
	},
	---@enum TooltipSide
	TooltipSide = {
		Left = 0,
		Right = 1,
		Top = 2,
		Bottom = 3,
	},
	---@enum TooltipTextureAnchor
	TooltipTextureAnchor = {
		LeftTop = 0,
		LeftCenter = 1,
		LeftBottom = 2,
		RightTop = 3,
		RightCenter = 4,
		RightBottom = 5,
		All = 6,
	},
	---@enum TooltipTextureRelativeRegion
	TooltipTextureRelativeRegion = {
		LeftLine = 0,
		RightLine = 1,
	},
	---@enum TrackedSpellCategory
	TrackedSpellCategory = {
		Offensive = 0,
		Defensive = 1,
		Debuff = 2,
		Count = 3,
	},
	---@enum TransmogCameraVariation
	TransmogCameraVariation = {
		None = 0,
		CloakBackpack = 1,
		RightShoulder = 1,
	},
	---@enum TransmogCollectionType
	TransmogCollectionType = {
		None = 0,
		Head = 1,
		Shoulder = 2,
		Back = 3,
		Chest = 4,
		Shirt = 5,
		Tabard = 6,
		Wrist = 7,
		Hands = 8,
		Waist = 9,
		Legs = 10,
		Feet = 11,
		Wand = 12,
		OneHAxe = 13,
		OneHSword = 14,
		OneHMace = 15,
		Dagger = 16,
		Fist = 17,
		Shield = 18,
		Holdable = 19,
		TwoHAxe = 20,
		TwoHSword = 21,
		TwoHMace = 22,
		Staff = 23,
		Polearm = 24,
		Bow = 25,
		Gun = 26,
		Crossbow = 27,
		Warglaives = 28,
		Paired = 29,
	},
	---@enum TransmogIllisionFlags
	TransmogIllisionFlags = {
		HideUntilCollected = 1,
		PlayerConditionGrantsOnLogin = 2,
	},
	---@enum TransmogModification
	TransmogModification = {
		Main = 0,
		Secondary = 1,
	},
	---@enum TransmogPendingType
	TransmogPendingType = {
		Apply = 0,
		Revert = 1,
		ToggleOn = 2,
		ToggleOff = 3,
	},
	---@enum TransmogSearchType
	TransmogSearchType = {
		Items = 1,
		BaseSets = 2,
		UsableSets = 3,
	},
	---@enum TransmogSlot
	TransmogSlot = {
		Head = 0,
		Shoulder = 1,
		Back = 2,
		Chest = 3,
		Body = 4,
		Tabard = 5,
		Wrist = 6,
		Hand = 7,
		Waist = 8,
		Legs = 9,
		Feet = 10,
		Mainhand = 11,
		Offhand = 12,
	},
	---@enum TransmogSource
	TransmogSource = {
		None = 0,
		JournalEncounter = 1,
		Quest = 2,
		Vendor = 3,
		WorldDrop = 4,
		HiddenUntilCollected = 5,
		CantCollect = 6,
		Achievement = 7,
		Profession = 8,
		NotValidForTransmog = 9,
	},
	---@enum TransmogType
	TransmogType = {
		Appearance = 0,
		Illusion = 1,
	},
	---@enum TransmogUseErrorType
	TransmogUseErrorType = {
		None = 0,
		PlayerCondition = 1,
		Skill = 2,
		Ability = 3,
		Faction = 4,
		Holiday = 5,
		HotRecheckFailed = 6,
	},
	---@enum TtsBoolSetting
	TtsBoolSetting = {
		PlaySoundSeparatingChatLineBreaks = 0,
		AddCharacterNameToSpeech = 1,
		PlayActivitySoundWhenNotFocused = 2,
		AlternateSystemVoice = 3,
		NarrateMyMessages = 4,
	},
	---@enum TtsVoiceType
	TtsVoiceType = {
		Standard = 0,
		Alternate = 1,
	},
	---@enum UICursorType
	UICursorType = {
		Default = 0,
		Item = 1,
		Money = 2,
		Spell = 3,
		PetAction = 4,
		Merchant = 5,
		ActionBar = 6,
		Macro = 7,
		AmmoObsolete = 9,
		Pet = 10,
		GuildBank = 11,
		GuildBankMoney = 12,
		EquipmentSet = 13,
		Currency = 14,
		Flyout = 15,
		VoidItem = 16,
		BattlePet = 17,
		Mount = 18,
		Toy = 19,
		ConduitCollectionItem = 20,
	},
	---@enum UIFrameType
	UIFrameType = {
		JailersTowerBuffs = 0,
	},
	---@enum UIItemInteractionFlags
	UIItemInteractionFlags = {
		DisplayWithInset = 1,
		ConfirmationHasDelay = 2,
		ConversionMode = 4,
		ClickShowsFlyout = 8,
	},
	---@enum UIItemInteractionType
	UIItemInteractionType = {
		None = 0,
		CastSpell = 1,
		CleanseCorruption = 2,
		RunecarverScrapping = 3,
		ItemConversion = 4,
	},
	---@enum UIMapFlag
	UIMapFlag = {
		NoHighlight = 1,
		ShowOverlays = 2,
		ShowTaxiNodes = 4,
		GarrisonMap = 8,
		FallbackToParentMap = 16,
		NoHighlightTexture = 32,
		ShowTaskObjectives = 64,
		NoWorldPositions = 128,
		HideArchaeologyDigs = 256,
		Deprecated = 512,
		HideIcons = 1024,
		HideVignettes = 2048,
		ForceAllOverlayExplored = 4096,
		FlightMapShowZoomOut = 8192,
		FlightMapAutoZoom = 16384,
		ForceOnNavbar = 32768,
		AlwaysAllowUserWaypoints = 65536,
	},
	---@enum UIMapSystem
	UIMapSystem = {
		World = 0,
		Taxi = 1,
		Adventure = 2,
		Minimap = 3,
	},
	---@enum UIMapType
	UIMapType = {
		Cosmic = 0,
		World = 1,
		Continent = 2,
		Zone = 3,
		Dungeon = 4,
		Micro = 5,
		Orphan = 6,
	},
	---@enum UIWidgetBlendModeType
	UIWidgetBlendModeType = {
		Opaque = 0,
		Additive = 1,
	},
	---@enum UIWidgetFlag
	UIWidgetFlag = {
		UniversalWidget = 1,
	},
	---@enum UIWidgetFontType
	UIWidgetFontType = {
		Normal = 0,
		Shadow = 1,
		Outline = 2,
	},
	---@enum UIWidgetLayoutDirection
	UIWidgetLayoutDirection = {
		Default = 0,
		Vertical = 1,
		Horizontal = 2,
		Overlap = 3,
		HorizontalForceNewRow = 4,
	},
	---@enum UIWidgetModelSceneLayer
	UIWidgetModelSceneLayer = {
		None = 0,
		Front = 1,
		Back = 2,
	},
	---@enum UIWidgetMotionType
	UIWidgetMotionType = {
		Instant = 0,
		Smooth = 1,
	},
	---@enum UIWidgetScale
	UIWidgetScale = {
		OneHundred = 0,
		Ninty = 1,
		Eighty = 2,
		Seventy = 3,
		Sixty = 4,
		Fifty = 5,
	},
	---@enum UIWidgetSetLayoutDirection
	UIWidgetSetLayoutDirection = {
		Vertical = 0,
		Horizontal = 1,
	},
	---@enum UIWidgetTextSizeType
	UIWidgetTextSizeType = {
		Small = 0,
		Medium = 1,
		Large = 2,
		Huge = 3,
		Standard = 4,
	},
	---@enum UIWidgetTooltipLocation
	UIWidgetTooltipLocation = {
		Default = 0,
		BottomLeft = 1,
		Left = 2,
		TopLeft = 3,
		Top = 4,
		TopRight = 5,
		Right = 6,
		BottomRight = 7,
		Bottom = 8,
	},
	---@enum UIWidgetVisualizationType
	UIWidgetVisualizationType = {
		IconAndText = 0,
		CaptureBar = 1,
		StatusBar = 2,
		DoubleStatusBar = 3,
		IconTextAndBackground = 4,
		DoubleIconAndText = 5,
		StackedResourceTracker = 6,
		IconTextAndCurrencies = 7,
		TextWithState = 8,
		HorizontalCurrencies = 9,
		BulletTextList = 10,
		ScenarioHeaderCurrenciesAndBackground = 11,
		TextureAndText = 12,
		SpellDisplay = 13,
		DoubleStateIconRow = 14,
		TextureAndTextRow = 15,
		ZoneControl = 16,
		CaptureZone = 17,
		TextureWithAnimation = 18,
		DiscreteProgressSteps = 19,
		ScenarioHeaderTimer = 20,
		TextColumnRow = 21,
		Spacer = 22,
		UnitPowerBar = 23,
	},
	---@enum UnitSex
	UnitSex = {
		Male = 0,
		Female = 1,
		None = 2,
		Both = 3,
	},
	---@enum ValidateNameResult
	ValidateNameResult = {
		NameSuccess = 0,
		NameFailure = 1,
		NameNoName = 2,
		NameTooShort = 3,
		NameTooLong = 4,
		NameInvalidCharacter = 5,
		NameMixedLanguages = 6,
		NameProfane = 7,
		NameReserved = 8,
		NameInvalidApostrophe = 9,
		NameMultipleApostrophes = 10,
		NameThreeConsecutive = 11,
		NameInvalidSpace = 12,
		NameConsecutiveSpaces = 13,
		NameRussianConsecutiveSilentCharacters = 14,
		NameRussianSilentCharacterAtBeginningOrEnd = 15,
		NameDeclensionDoesntMatchBaseName = 16,
		NameSpacesDisallowed = 17,
	},
	---@enum VasPurchaseProgress
	VasPurchaseProgress = {
		Invalid = 0,
		PrePurchase = 1,
		PaymentPending = 2,
		ApplyingLicense = 3,
		WaitingOnQueue = 4,
		Ready = 5,
		ProcessingFactionChange = 6,
		Complete = 7,
	},
	---@enum VignetteType
	VignetteType = {
		Normal = 0,
		PvPBounty = 1,
		Torghast = 2,
		Treasure = 3,
	},
	---@enum VoiceChannelErrorReason
	VoiceChannelErrorReason = {
		Unknown = 0,
		IsBattleNetChannel = 1,
	},
	---@enum VoiceChatStatusCode
	VoiceChatStatusCode = {
		Success = 0,
		OperationPending = 1,
		TooManyRequests = 2,
		LoginProhibited = 3,
		ClientNotInitialized = 4,
		ClientNotLoggedIn = 5,
		ClientAlreadyLoggedIn = 6,
		ChannelNameTooShort = 7,
		ChannelNameTooLong = 8,
		ChannelAlreadyExists = 9,
		AlreadyInChannel = 10,
		TargetNotFound = 11,
		Failure = 12,
		ServiceLost = 13,
		UnableToLaunchProxy = 14,
		ProxyConnectionTimeOut = 15,
		ProxyConnectionUnableToConnect = 16,
		ProxyConnectionUnexpectedDisconnect = 17,
		Disabled = 18,
		UnsupportedChatChannelType = 19,
		InvalidCommunityStream = 20,
		PlayerSilenced = 21,
		PlayerVoiceChatParentalDisabled = 22,
		InvalidInputDevice = 23,
		InvalidOutputDevice = 24,
	},
	---@enum VoiceTtsDestination
	VoiceTtsDestination = {
		RemoteTransmission = 0,
		LocalPlayback = 1,
		RemoteTransmissionWithLocalPlayback = 2,
		QueuedRemoteTransmission = 3,
		QueuedLocalPlayback = 4,
		QueuedRemoteTransmissionWithLocalPlayback = 5,
		ScreenReader = 6,
	},
	---@enum VoiceTtsStatusCode
	VoiceTtsStatusCode = {
		Success = 0,
		InvalidEngineType = 1,
		EngineAllocationFailed = 2,
		NotSupported = 3,
		MaxCharactersExceeded = 4,
		UtteranceBelowMinimumDuration = 5,
		InputTextEnqueued = 6,
		SdkNotInitialized = 7,
		DestinationQueueFull = 8,
		EnqueueNotNecessary = 9,
		UtteranceNotFound = 10,
		ManagerNotFound = 11,
		InvalidArgument = 12,
		InternalError = 13,
	},
	---@enum WeeklyRewardChestThresholdType
	WeeklyRewardChestThresholdType = {
		None = 0,
		MythicPlus = 1,
		RankedPvP = 2,
		Raid = 3,
		AlsoReceive = 4,
		Concession = 5,
	},
	---@enum WidgetAnimationType
	WidgetAnimationType = {
		None = 0,
		Fade = 1,
	},
	---@enum WidgetCurrencyClass
	WidgetCurrencyClass = {
		Currency = 0,
		Item = 1,
	},
	---@enum WidgetEnabledState
	WidgetEnabledState = {
		Disabled = 0,
		Enabled = 1,
		Red = 2,
		White = 3,
		Green = 4,
		Gold = 5,
		Black = 6,
	},
	---@enum WidgetShownState
	WidgetShownState = {
		Hidden = 0,
		Shown = 1,
	},
	---@enum WidgetTextHorizontalAlignmentType
	WidgetTextHorizontalAlignmentType = {
		Left = 0,
		Center = 1,
		Right = 2,
	},
	---@enum WidgetUnitPowerBarFlashMomentType
	WidgetUnitPowerBarFlashMomentType = {
		FlashWhenMax = 0,
		FlashWhenMin = 1,
		NeverFlash = 2,
	},
	---@enum WoWEntitlementType
	WoWEntitlementType = {
		Item = 0,
		Mount = 1,
		Battlepet = 2,
		Toy = 3,
		Appearance = 4,
		AppearanceSet = 5,
		GameTime = 6,
		Title = 7,
		Illusion = 8,
		Invalid = 9,
	},
	---@enum WorldQuestQuality
	WorldQuestQuality = {
		Common = 0,
		Rare = 1,
		Epic = 2,
	},
	---@enum ZoneControlActiveState
	ZoneControlActiveState = {
		Inactive = 0,
		Active = 1,
	},
	---@enum ZoneControlDangerFlashType
	ZoneControlDangerFlashType = {
		ShowOnGoodStates = 0,
		ShowOnBadStates = 1,
		ShowOnBoth = 2,
		ShowOnNeither = 3,
	},
	---@enum ZoneControlFillType
	ZoneControlFillType = {
		SingleFillClockwise = 0,
		SingleFillCounterClockwise = 1,
		DoubleFillClockwise = 2,
		DoubleFillCounterClockwise = 3,
	},
	---@enum ZoneControlLeadingEdgeType
	ZoneControlLeadingEdgeType = {
		NoLeadingEdge = 0,
		UseLeadingEdge = 1,
	},
	---@enum ZoneControlMode
	ZoneControlMode = {
		BothStatesAreGood = 0,
		State1IsGood = 1,
		State2IsGood = 2,
		NeitherStateIsGood = 3,
	},
	---@enum ZoneControlState
	ZoneControlState = {
		State1 = 0,
		State2 = 1,
	},
}

Constants = {
	CalendarGetEventTypeConstants = {
		DEFAULT_CALENDAR_GET_EVENT_TYPE = 0,
	},
	Callings = {
		MaxCallings = 3,
	},
	CurrencyConsts = {
		HONOR_PER_CURRENCY = 10,
		PLAYER_CURRENCY_CLIENT_FLAGS = 12,
		CONQUEST_ARENA_AND_BG_META_CURRENCY_ID = 483,
		CONQUEST_RATED_BG_META_CURRENCY_ID = 484,
		CONQUEST_ASHRAN_META_CURRENCY_ID = 692,
		ARTIFACT_KNOWLEDGE_CURRENCY_ID = 1171,
		WAR_RESOURCES_CURRENCY_ID = 1560,
		ACCOUNT_WIDE_HONOR_CURRENCY_ID = 1585,
		ACCOUNT_WIDE_HONOR_LEVEL_CURRENCY_ID = 1586,
		CONQUEST_CURRENCY_ID = 1602,
		HONOR_CURRENCY_ID = 1792,
		ECHOES_OF_NYALOTHA_CURRENCY_ID = 1803,
		CURRENCY_ID_WILLING_SOUL = 1810,
		CURRENCY_ID_RESERVOIR_ANIMA = 1813,
		CURRENCY_ID_RENOWN = 1822,
		CURRENCY_ID_RENOWN_KYRIAN = 1829,
		CURRENCY_ID_RENOWN_VENTHYR = 1830,
		CURRENCY_ID_RENOWN_NIGHT_FAE = 1831,
		CURRENCY_ID_RENOWN_NECROLORD = 1832,
		CLASSIC_ARENA_POINTS_CURRENCY_ID = 1900,
		CLASSIC_HONOR_CURRENCY_ID = 1901,
		QUESTIONMARK_INV_ICON = 134400,
		MAX_CURRENCY_QUANTITY = 100000000,
	},
	ITEM_WEAPON_SUBCLASSConstants = {
		ITEM_WEAPON_SUBCLASS_NONE = -1,
	},
	LevelConstsExposed = {
		MIN_RES_SICKNESS_LEVEL = 10,
	},
	ProfessionIDs = {
		PROFESSION_FIRST_AID = 129,
		PROFESSION_BLACKSMITHING = 164,
		PROFESSION_LEATHERWORKING = 165,
		PROFESSION_ALCHEMY = 171,
		PROFESSION_HERBALISM = 182,
		PROFESSION_COOKING = 185,
		PROFESSION_MINING = 186,
		PROFESSION_TAILORING = 197,
		PROFESSION_ENGINEERING = 202,
		PROFESSION_ENCHANTING = 333,
		PROFESSION_FISHING = 356,
		PROFESSION_SKINNING = 393,
		PROFESSION_JEWELCRAFTING = 755,
		PROFESSION_INSCRIPTION = 773,
		PROFESSION_ARCHAEOLOGY = 794,
	},
	PvpInfoConsts = {
		MaxPlayersPerInstance = 80,
	},
	QuestWatchConsts = {
		MAX_WORLD_QUEST_WATCHES_AUTOMATIC = 1,
		MAX_WORLD_QUEST_WATCHES_MANUAL = 5,
		MAX_QUEST_WATCHES = 25,
	},
	Transmog = {
		MainHandTransmogIsIndividualWeapon = -1,
		MainHandTransmogIsPairedWeapon = 0,
		NoTransmogID = 0,
	},
}
