---@meta _
---@class ModelLight
---@field omnidirectional boolean? Default = false
---@field point Vector3DMixin
---@field ambientIntensity number? Default = 0
---@field ambientColor ColorMixin?
---@field diffuseIntensity number? Default = 0
---@field diffuseColor ColorMixin?
