if not MAX_STABLE_SLOTS and Constants.PetConsts then
    MAX_STABLE_SLOTS = Constants.PetConsts.MAX_STABLE_SLOTS
    NUM_PET_SLOTS_THAT_NEED_LEARNED_SPELL = Constants.PetConsts.NUM_PET_SLOTS_THAT_NEED_LEARNED_SPELL
    EXTRA_PET_STABLE_SLOT = Constants.PetConsts.EXTRA_PET_STABLE_SLOT
end
