NUM_CHAT_WINDOWS = 10
MAX_WOW_CHAT_CHANNELS = 20

---@class ChatTypeInfo
---@field r number
---@field g number
---@field b number
---@field id number
---@field sticky number
---@field flashTab boolean
---@field flashTabOnGeneral boolean
---@field colorNameByClass boolean

---@type table<string, ChatTypeInfo>
ChatTypeInfo = {
	SYSTEM = {},
	SAY = {},
	PARTY = {},
	RAID = {},
	GUILD = {},
	OFFICER = {},
	YELL = {},
	WHISPER = {},
	SMART_WHISPER = {},
	WHISPER_INFORM = {},
	REPLY = {},
	EMOTE = {},
	TEXT_EMOTE = {},
	MONSTER_SAY = {},
	MONSTER_PARTY = {},
	MONSTER_YELL = {},
	MONSTER_WHISPER = {},
	MONSTER_EMOTE = {},
	CHANNEL = {},
	CHANNEL_JOIN = {},
	CHANNEL_LEAVE = {},
	CHANNEL_LIST = {},
	CHANNEL_NOTICE = {},
	CHANNEL_NOTICE_USER = {},
	TARGETICONS = {},
	AFK = {},
	DND = {},
	IGNORED = {},
	SKILL = {},
	LOOT = {},
	CURRENCY = {},
	MONEY = {},
	OPENING = {},
	TRADESKILLS = {},
	PET_INFO = {},
	COMBAT_MISC_INFO = {},
	COMBAT_XP_GAIN = {},
	COMBAT_HONOR_GAIN = {},
	COMBAT_FACTION_CHANGE = {},
	BG_SYSTEM_NEUTRAL = {},
	BG_SYSTEM_ALLIANCE = {},
	BG_SYSTEM_HORDE = {},
	RAID_LEADER = {},
	RAID_WARNING = {},
	RAID_BOSS_WHISPER = {},
	RAID_BOSS_EMOTE = {},
	QUEST_BOSS_EMOTE = {},
	FILTERED = {},
	INSTANCE_CHAT = {},
	INSTANCE_CHAT_LEADER = {},
	RESTRICTED = {},
	CHANNEL1 = {},
	CHANNEL2 = {},
	CHANNEL3 = {},
	CHANNEL4 = {},
	CHANNEL5 = {},
	CHANNEL6 = {},
	CHANNEL7 = {},
	CHANNEL8 = {},
	CHANNEL9 = {},
	CHANNEL10 = {},
	CHANNEL11 = {},
	CHANNEL12 = {},
	CHANNEL13 = {},
	CHANNEL14 = {},
	CHANNEL15 = {},
	CHANNEL16 = {},
	CHANNEL17 = {},
	CHANNEL18 = {},
	CHANNEL19 = {},
	CHANNEL20 = {},
	ACHIEVEMENT = {},
	GUILD_ACHIEVEMENT = {},
	PARTY_LEADER = {},
	BN_WHISPER = {},
	BN_WHISPER_INFORM = {},
	BN_ALERT = {},
	BN_BROADCAST = {},
	BN_BROADCAST_INFORM = {},
	BN_INLINE_TOAST_ALERT = {},
	BN_INLINE_TOAST_BROADCAST = {},
	BN_INLINE_TOAST_BROADCAST_INFORM = {},
	BN_WHISPER_PLAYER_OFFLINE = {},
	PET_BATTLE_COMBAT_LOG = {},
	PET_BATTLE_INFO = {},
	GUILD_ITEM_LOOTED = {},
	COMMUNITIES_CHANNEL = {},
}

SlashCmdList = {
	CONSOLE = function() end,
	CHATLOG = function() end,
	COMBATLOG = function() end,
	INVITE = function() end,
	REQUEST_INVITE = function() end,
	UNINVITE = function() end,
	PROMOTE = function() end,
	REPLY = function() end,
	HELP = function() end,
	MACROHELP = function() end,
	TIME = function() end,
	PLAYED = function() end,
	FOLLOW = function() end,
	TRADE = function() end,
	INSPECT = function() end,
	JOIN = function() end,
	LEAVE = function() end,
	LIST_CHANNEL = function() end,
	CHAT_HELP = function() end,
	CHAT_PASSWORD = function() end,
	CHAT_OWNER = function() end,
	CHAT_MODERATOR = function() end,
	CHAT_UNMODERATOR = function() end,
	CHAT_CINVITE = function() end,
	CHAT_KICK = function() end,
	CHAT_BAN = function() end,
	CHAT_UNBAN = function() end,
	CHAT_ANNOUNCE = function() end,
	GUILD_INVITE = function() end,
	GUILD_MOTD = function() end,
	GUILD_INFO = function() end,
	GUILD_ROSTER = function() end,
	CHAT_AFK = function() end,
	CHAT_DND = function() end,
	WHO = function() end,
	CHANNEL = function() end,
	FRIENDS = function() end,
	REMOVEFRIEND = function() end,
	IGNORE = function() end,
	UNIGNORE = function() end,
	SCRIPT = function() end,
	RANDOM = function() end,
	MACRO = function() end,
	PVP = function() end,
	RAID_INFO = function() end,
	READYCHECK = function() end,
	SAVEGUILDROSTER = function() end,
	DUNGEONS = function() end,
	BENCHMARK = function() end,
	DISMOUNT = function() end,
	LEAVEVEHICLE = function() end,
	RESETCHAT = function() end,
	ENABLE_ADDONS = function() end,
	DISABLE_ADDONS = function() end,
	STOPWATCH = function() end,
	CALENDAR = function() end,
	ACHIEVEMENTUI = function() end,
	SET_TITLE = function() end,
	USE_TALENT_SPEC = function() end,
	UI_ERRORS_OFF = function() end,
	UI_ERRORS_ON = function() end,
	FRAMESTACK = function() end,
	EVENTTRACE = function() end,
	TEXELVIS = function() end,
	TABLEINSPECT = function() end,
	DUMP = function() end,
	RELOAD = function() end,
	WARGAME = function() end,
	SPECTATOR_WARGAME = function() end,
	GUILDFINDER = function() end,
	TARGET_MARKER = function() end,
	OPEN_LOOT_HISTORY = function() end,
	RAIDFINDER = function() end,
	SHARE = function() end,
	API = function() end,
	COMMENTATOR_OVERRIDE = function() end,
	COMMENTATOR_NAMETEAM = function() end,
	COMMENTATOR_ASSIGNPLAYER = function() end,
	RESET_COMMENTATOR_SETTINGS = function() end,
	VOICECHAT = function() end,
	COMMUNITY = function() end,
	COUNTDOWN = function() end,
}

---@param callback function
---@param command string
---@param commandAlias string
---[FrameXML](https://www.townlong-yak.com/framexml/go/RegisterNewSlashCommand)
function RegisterNewSlashCommand(callback, command, commandAlias) end
