STANDARD_TEXT_FONT = "Fonts\\FRIZQT__.TTF"
UNIT_NAME_FONT = "Fonts\\FRIZQT__.TTF"
DAMAGE_TEXT_FONT = "Fonts\\FRIZQT__.TTF"

NAMEPLATE_FONT = "GameFontWhite"
NAMEPLATE_SPELLCAST_FONT = "GameFontWhiteTiny"
