---@meta
---[Documentation](https://wowpedia.fandom.com/wiki/Struct_FontInfo)
---@class FontInfo
---@field height number	
---@field outline string
---@field color table
---@field shadow FontShadow

---@class FontShadow
---@field x number	
---@field y number
---@field color table
