---@meta _
---@class TooltipComparisonLine
---@field text string
---@field color ColorMixin

---@class TooltipDataArg
---@field field string
---@field stringVal string?
---@field intVal number?
---@field floatVal number?
---@field boolVal boolean?
---@field colorVal ColorMixin?
---@field guidVal WOWGUID?
