C_Bank = {}

---@class BANK_BAG_SLOT_FLAGS_UPDATED
---@field slot number
local BANK_BAG_SLOT_FLAGS_UPDATED = {}

---@class BANKFRAME_CLOSED
local BANKFRAME_CLOSED = {}

---@class BANKFRAME_OPENED
local BANKFRAME_OPENED = {}

---@class PLAYERBANKBAGSLOTS_CHANGED
local PLAYERBANKBAGSLOTS_CHANGED = {}

---@class PLAYERBANKSLOTS_CHANGED
---@field slot number
local PLAYERBANKSLOTS_CHANGED = {}

---@class PLAYERREAGENTBANKSLOTS_CHANGED
---@field slot number
local PLAYERREAGENTBANKSLOTS_CHANGED = {}

---@class REAGENTBANK_PURCHASED
local REAGENTBANK_PURCHASED = {}

---@class REAGENTBANK_UPDATE
local REAGENTBANK_UPDATE = {}
