C_BarberShop = {}

---@class BARBER_SHOP_APPEARANCE_APPLIED
local BARBER_SHOP_APPEARANCE_APPLIED = {}

---@class BARBER_SHOP_CLOSE
local BARBER_SHOP_CLOSE = {}

---@class BARBER_SHOP_COST_UPDATE
local BARBER_SHOP_COST_UPDATE = {}

---@class BARBER_SHOP_OPEN
local BARBER_SHOP_OPEN = {}

---@class BARBER_SHOP_SUCCESS
local BARBER_SHOP_SUCCESS = {}
