C_GuildBank = {}

---@class GUILDBANK_ITEM_LOCK_CHANGED
local GUILDBANK_ITEM_LOCK_CHANGED = {}

---@class GUILDBANK_TEXT_CHANGED
---@field guildBankTab number
local GUILDBANK_TEXT_CHANGED = {}

---@class GUILDBANK_UPDATE_MONEY
local GUILDBANK_UPDATE_MONEY = {}

---@class GUILDBANK_UPDATE_TABS
local GUILDBANK_UPDATE_TABS = {}

---@class GUILDBANK_UPDATE_TEXT
---@field guildBankTab number
local GUILDBANK_UPDATE_TEXT = {}

---@class GUILDBANK_UPDATE_WITHDRAWMONEY
local GUILDBANK_UPDATE_WITHDRAWMONEY = {}

---@class GUILDBANKBAGSLOTS_CHANGED
local GUILDBANKBAGSLOTS_CHANGED = {}

---@class GUILDBANKFRAME_CLOSED
local GUILDBANKFRAME_CLOSED = {}

---@class GUILDBANKFRAME_OPENED
local GUILDBANKFRAME_OPENED = {}

---@class GUILDBANKLOG_UPDATE
local GUILDBANKLOG_UPDATE = {}
