C_KnowledgeBase = {}

---@class KNOWLEDGE_BASE_ARTICLE_LOAD_FAILURE
local KNOWLEDGE_BASE_ARTICLE_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_ARTICLE_LOAD_SUCCESS
local KNOWLEDGE_BASE_ARTICLE_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_QUERY_LOAD_FAILURE
local KNOWLEDGE_BASE_QUERY_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_QUERY_LOAD_SUCCESS
local KNOWLEDGE_BASE_QUERY_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_SERVER_MESSAGE
local KNOWLEDGE_BASE_SERVER_MESSAGE = {}

---@class KNOWLEDGE_BASE_SETUP_LOAD_FAILURE
local KNOWLEDGE_BASE_SETUP_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_SETUP_LOAD_SUCCESS
local KNOWLEDGE_BASE_SETUP_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_SYSTEM_MOTD_UPDATED
local KNOWLEDGE_BASE_SYSTEM_MOTD_UPDATED = {}
