C_KnowledgeBase = {}

---@class KNOWLEDGE_BASE_ARTICLE_LOAD_FAILURE : Event
local KNOWLEDGE_BASE_ARTICLE_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_ARTICLE_LOAD_SUCCESS : Event
local KNOWLEDGE_BASE_ARTICLE_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_QUERY_LOAD_FAILURE : Event
local KNOWLEDGE_BASE_QUERY_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_QUERY_LOAD_SUCCESS : Event
local KNOWLEDGE_BASE_QUERY_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_SERVER_MESSAGE : Event
local KNOWLEDGE_BASE_SERVER_MESSAGE = {}

---@class KNOWLEDGE_BASE_SETUP_LOAD_FAILURE : Event
local KNOWLEDGE_BASE_SETUP_LOAD_FAILURE = {}

---@class KNOWLEDGE_BASE_SETUP_LOAD_SUCCESS : Event
local KNOWLEDGE_BASE_SETUP_LOAD_SUCCESS = {}

---@class KNOWLEDGE_BASE_SYSTEM_MOTD_UPDATED : Event
local KNOWLEDGE_BASE_SYSTEM_MOTD_UPDATED = {}
