C_SecureTransfer = {}

---@class SECURE_TRANSFER_CANCEL : Event
local SECURE_TRANSFER_CANCEL = {}

---@class SECURE_TRANSFER_CONFIRM_SEND_MAIL : Event
local SECURE_TRANSFER_CONFIRM_SEND_MAIL = {}

---@class SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT : Event
local SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT = {}
