C_StableInfo = {}

---@class PET_STABLE_CLOSED
local PET_STABLE_CLOSED = {}

---@class PET_STABLE_SHOW
local PET_STABLE_SHOW = {}

---@class PET_STABLE_UPDATE
local PET_STABLE_UPDATE = {}

---@class PET_STABLE_UPDATE_PAPERDOLL
local PET_STABLE_UPDATE_PAPERDOLL = {}
