C_Trainer = {}

---@class TRAINER_CLOSED
local TRAINER_CLOSED = {}

---@class TRAINER_DESCRIPTION_UPDATE
local TRAINER_DESCRIPTION_UPDATE = {}

---@class TRAINER_SERVICE_INFO_NAME_UPDATE
local TRAINER_SERVICE_INFO_NAME_UPDATE = {}

---@class TRAINER_SHOW
local TRAINER_SHOW = {}

---@class TRAINER_UPDATE
local TRAINER_UPDATE = {}
