---@class SECURE_TRANSFER_CANCEL
---[Documentation](https://wow.gamepedia.com/SECURE_TRANSFER_CANCEL)
local SECURE_TRANSFER_CANCEL = {}

---@class SECURE_TRANSFER_CONFIRM_SEND_MAIL
---[Documentation](https://wow.gamepedia.com/SECURE_TRANSFER_CONFIRM_SEND_MAIL)
local SECURE_TRANSFER_CONFIRM_SEND_MAIL = {}

---@class SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT
---[Documentation](https://wow.gamepedia.com/SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT)
local SECURE_TRANSFER_CONFIRM_TRADE_ACCEPT = {}
