---@meta
---@class unk

---@alias ChatType
---|"SAY"
---|"EMOTE"
---|"YELL"
---|"PARTY"
---|"RAID"
---|"RAID_WARNING"
---|"INSTANCE_CHAT"
---|"GUILD"
---|"OFFICER"
---|"WHISPER"
---|"CHANNEL"
---|"AFK"
---|"DND"
---|"VOICE_TEXT"

---@alias ClassFile -- #41
---|"WARRIOR"     # 1
---|"PALADIN"     # 2
---|"HUNTER"      # 3
---|"ROGUE"       # 4
---|"PRIEST"      # 5
---|"DEATHKNIGHT" # 6
---|"SHAMAN"      # 7
---|"MAGE"        # 8
---|"WARLOCK"     # 9
---|"MONK"        # 10
---|"DRUID"       # 11
---|"DEMONHUNTER" # 12

---@alias HyperlinkType -- #41
---|"achievement"
---|"api"
---|"azessence"
---|"battlepet"
---|"battlePetAbil"
---|"calendarEvent"
---|"channel"
---|"clubFinder"
---|"clubTicket"
---|"community"
---|"conduit"
---|"currency"
---|"death"
---|"enchant"
---|"garrfollower"
---|"garrfollowerability"
---|"garrmission"
---|"instancelock"
---|"item"
---|"journal"
---|"keystone"
---|"levelup"
---|"lootHistory"
---|"outfit"
---|"player"
---|"playerCommunity"
---|"BNplayer"
---|"BNplayerCommunity"
---|"quest"
---|"shareachieve"
---|"shareitem"
---|"sharess"
---|"spell"
---|"storecategory"
---|"talent"
---|"trade"
---|"transmogappearance"
---|"transmogillusion"
---|"transmogset"
---|"unit"
---|"urlIndex"
---|"worldmap"

---@alias InventorySlotName
---|"AMMOSLOT"
---|"HEADSLOT"
---|"NECKSLOT"
---|"SHOULDERSLOT"
---|"SHIRTSLOT"
---|"CHESTSLOT"
---|"WAISTSLOT"
---|"LEGSSLOT"
---|"FEETSLOT"
---|"WRISTSLOT"
---|"HANDSSLOT"
---|"FINGER0SLOT"
---|"FINGER1SLOT"
---|"TRINKET0SLOT"
---|"TRINKET1SLOT"
---|"BACKSLOT"
---|"MAINHANDSLOT"
---|"SECONDARYHANDSLOT"
---|"RANGEDSLOT"
---|"TABARDSLOT"

---@alias UnitId
---|"player"
---|"target"
---|"focus"
---|"mouseover"
---|"pet"
---|"vehicle"
---|"npc"
---|"none"
---|"party1"
---|"raid1"
---|"nameplate1"
---|"arena1"
---|"boss1"

---@alias FramePoint
---|"TOPLEFT"
---|"TOPRIGHT"
---|"BOTTOMLEFT"
---|"BOTTOMRIGHT"
---|"TOP"
---|"BOTTOM"
---|"LEFT"
---|"RIGHT"
---|"CENTER"

---@alias InventorySlots number
